/// Flutter icons CsIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CsIcon
///      fonts:
///       - asset: fonts/CsIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CsIcon {
  CsIcon._();

  static const _kFontFam = 'CsIcon';

  static const IconData counter_spell = const IconData(0xe800, fontFamily: _kFontFam);
}
