/// Flutter icons CounterSpell
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CounterSpell
///      fonts:
///       - asset: fonts/CounterSpell.ttf
///
///
///
library;
// ignore_for_file: constant_identifier_names

import 'package:counter_spell/data/icon/mc_icons.dart';
import 'package:flutter/widgets.dart';

class CounterSpellIcons {
  CounterSpellIcons._();

  static const _kFontFam = 'CounterSpell';
  static const String? _kFontPkg = null;

  static const IconData damage_filled = IconData(
    0xe800,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData damage_outlined = IconData(
    0xe801,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counterspell = IconData(
    0xe802,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData cast_filled = IconData(
    0xe803,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData experience_filled = IconData(
    0xe804,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData poison_outlined = IconData(
    0xe807,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData cast_outlined = IconData(
    0xe808,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData experience_outlined = IconData(
    0xe80a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData poison_filled = IconData(
    0xe80b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );

  static const IconData attack = McIcons.sword_cross;

  static const IconData defense_outlined = McIcons.shield_outline;
  static const IconData defense_filled = McIcons.shield;
}
