/// Flutter icons MagicIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MagicIcons
///      fonts:
///       - asset: fonts/MagicIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';


class CSIconsRaw {

  static const _kFontFam1 = 'MagicIcons';
  static const _kFontFam2 = 'MaterialDesignIcons';
  static const _kFontFam3 = 'ShieldIcons';
  static const _kFontFam4 = 'Dices';

  static const _kFontFamCS = 'CounterSpell';

  static const IconData cast_filled = IconData(0xe800, fontFamily: _kFontFamCS);
  static const IconData cast_outlined = IconData(0xe801, fontFamily: _kFontFamCS);
  static const IconData counterspell = IconData(0xe802, fontFamily: _kFontFamCS);
  static const IconData damage_filled = IconData(0xe803, fontFamily: _kFontFamCS);
  static const IconData damage_outlined = IconData(0xe804, fontFamily: _kFontFamCS);

  static const IconData dice_1 = const IconData(0xf1ca, fontFamily: _kFontFam4);
  static const IconData dice_2 = const IconData(0xf1cb, fontFamily: _kFontFam4);
  static const IconData dice_3 = const IconData(0xf1cc, fontFamily: _kFontFam4);
  static const IconData dice_4 = const IconData(0xf1cd, fontFamily: _kFontFam4);
  static const IconData dice_5 = const IconData(0xf1ce, fontFamily: _kFontFam4);
  static const IconData dice_6 = const IconData(0xf1cf, fontFamily: _kFontFam4);
  static const IconData dice_d20 = const IconData(0xf5ea, fontFamily: _kFontFam4);
  static const IconData coins = const IconData(0xf694, fontFamily: _kFontFam4);

  static const IconData experience_filled = const IconData(0xe802, fontFamily: _kFontFam1);
  static const IconData experience_outlined = const IconData(0xe803, fontFamily: _kFontFam1);
  static const IconData phyrexia = const IconData(0xe804, fontFamily: _kFontFam1);

  static const IconData skull_crossbones = const IconData(0xe800, fontFamily: _kFontFam2);
  static const IconData skull_crossbones_outline = const IconData(0xe801, fontFamily: _kFontFam2);
  static const IconData skull_outline = const IconData(0xe802, fontFamily: _kFontFam2);
  static const IconData sword = const IconData(0xf4e5, fontFamily: _kFontFam2);
  static const IconData skull = const IconData(0xf68b, fontFamily: _kFontFam2);
  static const IconData sword_cross = const IconData(0xf786, fontFamily: _kFontFam2);

  static const IconData shield_off = const IconData(0xe800, fontFamily: _kFontFam3);
  static const IconData shield_off_outline = const IconData(0xe801, fontFamily: _kFontFam3);
  static const IconData shield_check_outline = const IconData(0xe802, fontFamily: _kFontFam3);
  static const IconData shield_account_outline = const IconData(0xe803, fontFamily: _kFontFam3);
  static const IconData shield_plus = const IconData(0xe804, fontFamily: _kFontFam3);
  static const IconData shield_plus_outline = const IconData(0xe805, fontFamily: _kFontFam3);
  static const IconData shield_remove = const IconData(0xe806, fontFamily: _kFontFam3);
  static const IconData shield_remove_outline = const IconData(0xe807, fontFamily: _kFontFam3);
  static const IconData shield = const IconData(0xf498, fontFamily: _kFontFam3);
  static const IconData shield_outline = const IconData(0xf499, fontFamily: _kFontFam3);
  static const IconData shield_check = const IconData(0xf565, fontFamily: _kFontFam3);
  static const IconData shield_half_full = const IconData(0xf77f, fontFamily: _kFontFam3);
  static const IconData shield_account = const IconData(0xf88e, fontFamily: _kFontFam3);

}


