// Flutter icons Keyrune
// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
// This font was generated by FlutterIcon.com, which is derived from Fontello.
//
// To use this font, place it in your fonts/ directory and include the
// following in your pubspec.yaml
//
// flutter:
//   fonts:
//    - family:  Keyrune
//      fonts:
//       - asset: fonts/Keyrune.ttf
//
//
//
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class Keyrune {
  Keyrune._();

  static const _kFontFam = 'Keyrune';
  static const String? _kFontPkg = null;

  static const IconData lea = IconData(
    0xe800,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData leb = IconData(
    0xe801,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i2ed = IconData(
    0xe802,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i3ed = IconData(
    0xe803,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i4ed = IconData(
    0xe804,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData psum = IconData(
    0xe805,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i5ed = IconData(
    0xe806,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i6ed = IconData(
    0xe807,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i7ed = IconData(
    0xe808,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i8ed = IconData(
    0xe809,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i9ed = IconData(
    0xe80a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i10e = IconData(
    0xe80b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData m10 = IconData(
    0xe80c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData m11 = IconData(
    0xe80d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData m12 = IconData(
    0xe80e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData m13 = IconData(
    0xe80f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData m14 = IconData(
    0xe810,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData m15 = IconData(
    0xe811,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData bcore = IconData(
    0xe812,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData arn = IconData(
    0xe813,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData atq = IconData(
    0xe814,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData leg = IconData(
    0xe815,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData drk = IconData(
    0xe816,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData fem = IconData(
    0xe817,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData hml = IconData(
    0xe818,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ice = IconData(
    0xe819,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData all = IconData(
    0xe81a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData csp = IconData(
    0xe81b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mir = IconData(
    0xe81c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData vis = IconData(
    0xe81d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData wth = IconData(
    0xe81e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tmp = IconData(
    0xe81f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sth = IconData(
    0xe820,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData exo = IconData(
    0xe821,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData usg = IconData(
    0xe822,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ulg = IconData(
    0xe823,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData uds = IconData(
    0xe824,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mmq = IconData(
    0xe825,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData nms__nem = IconData(
    0xe826,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pcy = IconData(
    0xe827,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData van = IconData(
    0xe828,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData cmd = IconData(
    0xe829,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData cm1 = IconData(
    0xe82a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData c13 = IconData(
    0xe82b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pc2 = IconData(
    0xe82c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData arc__ann = IconData(
    0xe82d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData hop = IconData(
    0xe82e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData cns = IconData(
    0xe82f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData c14 = IconData(
    0xe830,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData chr = IconData(
    0xe831,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ath = IconData(
    0xe832,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData brb = IconData(
    0xe833,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData btd = IconData(
    0xe834,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mma = IconData(
    0xe835,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData s99 = IconData(
    0xe836,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ptk = IconData(
    0xe837,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dd2 = IconData(
    0xe838,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ddc = IconData(
    0xe839,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ddg = IconData(
    0xe83a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ddj = IconData(
    0xe83b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ddk = IconData(
    0xe83c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ddl = IconData(
    0xe83d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ddm = IconData(
    0xe83e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ddn = IconData(
    0xe83f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ddo = IconData(
    0xe840,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ddi = IconData(
    0xe841,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ddh = IconData(
    0xe842,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ddd = IconData(
    0xe843,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dde = IconData(
    0xe844,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData drb = IconData(
    0xe845,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData v09 = IconData(
    0xe846,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData v10 = IconData(
    0xe847,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData v11 = IconData(
    0xe848,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData v12 = IconData(
    0xe849,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData v13 = IconData(
    0xe84a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData v14 = IconData(
    0xe84b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData h09 = IconData(
    0xe84c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pd2 = IconData(
    0xe84d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pd3 = IconData(
    0xe84e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData md1 = IconData(
    0xe84f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pgru = IconData(
    0xe850,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pmtg1 = IconData(
    0xe851,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pmtg2 = IconData(
    0xe852,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pleaf = IconData(
    0xe853,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pmei = IconData(
    0xe854,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData parl = IconData(
    0xe855,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dpa = IconData(
    0xe856,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pbook = IconData(
    0xe857,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData past = IconData(
    0xe858,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData me2 = IconData(
    0xe859,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData me1 = IconData(
    0xe85a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData parl2 = IconData(
    0xe85b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData por = IconData(
    0xe85c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ths = IconData(
    0xe85d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData fut = IconData(
    0xe85e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData inv = IconData(
    0xe85f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pls = IconData(
    0xe860,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData lrw = IconData(
    0xe861,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData bng = IconData(
    0xe862,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData po2 = IconData(
    0xe863,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData jou = IconData(
    0xe864,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mor = IconData(
    0xe865,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData apc = IconData(
    0xe866,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ody = IconData(
    0xe867,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tor = IconData(
    0xe868,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData jud = IconData(
    0xe869,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ons = IconData(
    0xe86a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData lgn = IconData(
    0xe86b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData scg = IconData(
    0xe86c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mrd = IconData(
    0xe86d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dst = IconData(
    0xe86e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i5dn = IconData(
    0xe86f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData chk = IconData(
    0xe870,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData bok = IconData(
    0xe871,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sok = IconData(
    0xe872,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rav = IconData(
    0xe873,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData gpt = IconData(
    0xe874,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dis = IconData(
    0xe875,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tsp = IconData(
    0xe876,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData plc = IconData(
    0xe877,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dgm = IconData(
    0xe878,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData gtc = IconData(
    0xe879,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dkm = IconData(
    0xe87a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rtr = IconData(
    0xe87b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData avr = IconData(
    0xe87c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dka = IconData(
    0xe87d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData isd = IconData(
    0xe87e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData nph = IconData(
    0xe87f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mbs = IconData(
    0xe880,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData som = IconData(
    0xe881,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData roe = IconData(
    0xe882,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData wwk = IconData(
    0xe883,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData zen = IconData(
    0xe884,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData arb = IconData(
    0xe885,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData con = IconData(
    0xe886,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ala = IconData(
    0xe887,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData eve = IconData(
    0xe888,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData shm = IconData(
    0xe889,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ktk = IconData(
    0xe88a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData frf = IconData(
    0xe88b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData s00 = IconData(
    0xe88c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData evg = IconData(
    0xe88d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ddf = IconData(
    0xe88e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData me3 = IconData(
    0xe88f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData me4 = IconData(
    0xe890,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ugl = IconData(
    0xe891,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData unh = IconData(
    0xe892,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dtk = IconData(
    0xe893,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tpr = IconData(
    0xe894,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mm2 = IconData(
    0xe895,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData exp = IconData(
    0xe896,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData bfz = IconData(
    0xe897,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ddp = IconData(
    0xe898,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ori = IconData(
    0xe899,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData vma = IconData(
    0xe89a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData c15 = IconData(
    0xe900,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ogw = IconData(
    0xe901,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData soi = IconData(
    0xe902,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ema = IconData(
    0xe903,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData cn2 = IconData(
    0xe904,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData v15 = IconData(
    0xe905,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData v16 = IconData(
    0xe906,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData w16 = IconData(
    0xe907,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ddq = IconData(
    0xe908,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData psalvat05 = IconData(
    0xe909,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData psalvat11 = IconData(
    0xe90a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData emn = IconData(
    0xe90b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData xlcu__pz1 = IconData(
    0xe90c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ddr = IconData(
    0xe90d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData kld = IconData(
    0xe90e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData aer = IconData(
    0xe90f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData c16 = IconData(
    0xe910,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pca = IconData(
    0xe911,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mm3 = IconData(
    0xe912,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mp1 = IconData(
    0xe913,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData akh = IconData(
    0xe914,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pxbox = IconData(
    0xe915,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData cma = IconData(
    0xe916,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData xren = IconData(
    0xe917,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData xrin = IconData(
    0xe918,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pmps = IconData(
    0xe919,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pmpu = IconData(
    0xe91a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pmodo = IconData(
    0xe91b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData td2 = IconData(
    0xe91c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData xduels = IconData(
    0xe91d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData xmods = IconData(
    0xe91e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pz2__pmotc = IconData(
    0xe91f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData v0x = IconData(
    0xe920,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dds = IconData(
    0xe921,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mp2 = IconData(
    0xe922,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData w17 = IconData(
    0xe923,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData hou = IconData(
    0xe924,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ice2 = IconData(
    0xe925,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData xcle = IconData(
    0xe926,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData xice = IconData(
    0xe927,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData x2ps = IconData(
    0xe928,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData x4ea = IconData(
    0xe929,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData papac = IconData(
    0xe92a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData peuro = IconData(
    0xe92b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pidw = IconData(
    0xe92c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData e01 = IconData(
    0xe92d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData xln = IconData(
    0xe92e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rix = IconData(
    0xe92f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ust = IconData(
    0xe930,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData e02 = IconData(
    0xe931,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pdgc = IconData(
    0xe932,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ddt = IconData(
    0xe933,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData c17 = IconData(
    0xe934,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ima = IconData(
    0xe935,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pheart = IconData(
    0xe936,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pfnm = IconData(
    0xe937,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData h17 = IconData(
    0xe938,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData v17 = IconData(
    0xe939,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pdep = IconData(
    0xe93a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData psega = IconData(
    0xe93b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ptsa = IconData(
    0xe93c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData a25 = IconData(
    0xe93d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ddu = IconData(
    0xe93e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dom = IconData(
    0xe93f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData cm2 = IconData(
    0xe940,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData m19 = IconData(
    0xe941,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData bbd = IconData(
    0xe942,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData parl3 = IconData(
    0xe943,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ss1 = IconData(
    0xe944,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData gs1 = IconData(
    0xe945,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData c18 = IconData(
    0xe946,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData x1e = IconData(
    0xe947,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData x2e = IconData(
    0xe948,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData x2u = IconData(
    0xe949,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData x3e = IconData(
    0xe94a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData grn__gk1 = IconData(
    0xe94b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData med = IconData(
    0xe94c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData gnt = IconData(
    0xe94d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData azorius = IconData(
    0xe94e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData boros = IconData(
    0xe94f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dimir = IconData(
    0xe950,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData golgari = IconData(
    0xe951,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData gruul = IconData(
    0xe952,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData izzet = IconData(
    0xe953,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData orzhov = IconData(
    0xe954,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rakdos = IconData(
    0xe955,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData selesnya = IconData(
    0xe956,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData simic = IconData(
    0xe957,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData uma = IconData(
    0xe958,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rna = IconData(
    0xe959,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData war = IconData(
    0xe95a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mh1 = IconData(
    0xe95b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ss2 = IconData(
    0xe95c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData m20 = IconData(
    0xe95d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData eld = IconData(
    0xe95e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData c19 = IconData(
    0xe95f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData m21 = IconData(
    0xe960,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData thb = IconData(
    0xe961,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData iko__xikr = IconData(
    0xe962,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData znr = IconData(
    0xe963,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData gn2 = IconData(
    0xe964,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ptg = IconData(
    0xe965,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData c20 = IconData(
    0xe966,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData znc = IconData(
    0xe967,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData cc1 = IconData(
    0xe968,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData cmr__cmc = IconData(
    0xe969,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData j20 = IconData(
    0xe96a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ha1 = IconData(
    0xe96b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData und = IconData(
    0xe96c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ss3 = IconData(
    0xe96d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i2xm = IconData(
    0xe96e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData jmp = IconData(
    0xe96f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData akr = IconData(
    0xe970,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mb1 = IconData(
    0xe971,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData afr = IconData(
    0xe972,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData afr_border = IconData(
    0xe973,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData khm = IconData(
    0xe974,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData stx = IconData(
    0xe975,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tsr = IconData(
    0xe976,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData vow = IconData(
    0xe977,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mid = IconData(
    0xe978,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mid_border = IconData(
    0xe979,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData zne = IconData(
    0xe97a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mh2 = IconData(
    0xe97b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData klr = IconData(
    0xe97c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData khc = IconData(
    0xe97d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData c21 = IconData(
    0xe97e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData c21_border = IconData(
    0xe97f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sta = IconData(
    0xe980,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData afc = IconData(
    0xe981,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData afc_border = IconData(
    0xe982,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData j21 = IconData(
    0xe983,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData j21_outline = IconData(
    0xe984,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mic = IconData(
    0xe985,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData voc = IconData(
    0xe986,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData cc2 = IconData(
    0xe987,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData cc2_border = IconData(
    0xe988,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData y22 = IconData(
    0xe989,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData unf = IconData(
    0xe98a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData snc = IconData(
    0xe98b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData neo = IconData(
    0xe98c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData nec = IconData(
    0xe98d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ncc = IconData(
    0xe98e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ncc_color = IconData(
    0xe98f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ncc_white = IconData(
    0xe990,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData clb = IconData(
    0xe991,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData clb_white = IconData(
    0xe992,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dmu = IconData(
    0xe993,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dmc = IconData(
    0xe994,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dmc_color = IconData(
    0xe995,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dmc_border = IconData(
    0xe996,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dmc_white = IconData(
    0xe997,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i40k = IconData(
    0xe998,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i40k_color = IconData(
    0xe999,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i40k_border = IconData(
    0xe99a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i40k_white = IconData(
    0xe99b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i2x2 = IconData(
    0xe99c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData bro = IconData(
    0xe99d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData bot = IconData(
    0xe99e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData brc = IconData(
    0xe99f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData brr = IconData(
    0xe9a0,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData one = IconData(
    0xe9a1,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mom = IconData(
    0xe9a2,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mat = IconData(
    0xe9a3,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dmr = IconData(
    0xe9a4,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData gn3 = IconData(
    0xe9a5,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData hbg = IconData(
    0xe9a6,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ydmu__y23 = IconData(
    0xe9a7,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData onc = IconData(
    0xe9a8,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData moc = IconData(
    0xe9a9,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i30a = IconData(
    0xe9aa,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData scd = IconData(
    0xe9ab,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData scd_white = IconData(
    0xe9ac,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData j22 = IconData(
    0xe9ad,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData woe = IconData(
    0xe9ae,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ltr = IconData(
    0xe9af,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData who = IconData(
    0xe9b0,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sir = IconData(
    0xe9b1,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sis = IconData(
    0xe9b2,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sis_color = IconData(
    0xe9b3,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ea1 = IconData(
    0xe9b4,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData cmm = IconData(
    0xe9b5,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ltc = IconData(
    0xe9b6,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ltc_color = IconData(
    0xe9b7,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ltc_white = IconData(
    0xe9b8,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData woc = IconData(
    0xe9b9,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mul = IconData(
    0xe9ba,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rvr = IconData(
    0xe9bb,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sld2 = IconData(
    0xe9bc,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData y24 = IconData(
    0xe9bd,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData una = IconData(
    0xe9be,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData una_white = IconData(
    0xe9bf,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData wot = IconData(
    0xe9c0,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br = IconData(
    0xe9c1,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData lci = IconData(
    0xe9c2,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pip = IconData(
    0xe9c3,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rex = IconData(
    0xe9c4,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData khc_rarity = IconData(
    0xe9c5,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData khc_inner = IconData(
    0xe9c6,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData lcc = IconData(
    0xe9c7,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData spg = IconData(
    0xe9c8,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mkm = IconData(
    0xe9c9,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mkc = IconData(
    0xe9ca,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData clu = IconData(
    0xe9cb,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData otj = IconData(
    0xe9cc,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData blb = IconData(
    0xe9cd,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData acr = IconData(
    0xe9ce,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mh3 = IconData(
    0xe9cf,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData m3c = IconData(
    0xe9d0,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData m3c_inner = IconData(
    0xe9d1,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData otc = IconData(
    0xe9d2,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData otc_inner = IconData(
    0xe9d3,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData blc = IconData(
    0xe9d4,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData otp = IconData(
    0xe9d5,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData big = IconData(
    0xe9d6,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dsk = IconData(
    0xe9d7,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData fdn = IconData(
    0xe9d8,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mb2 = IconData(
    0xe9d9,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData y25__yblb = IconData(
    0xe9da,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData j25 = IconData(
    0xe9db,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dsc = IconData(
    0xe9dc,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dsc_border = IconData(
    0xe9dd,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dsc_white = IconData(
    0xe9de,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData j25_alt = IconData(
    0xe9df,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dft = IconData(
    0xe9e0,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dft_rarity = IconData(
    0xe9e1,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData inr = IconData(
    0xe9e2,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData inr_border = IconData(
    0xe9e3,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData fdc = IconData(
    0xe9e4,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData c16_border = IconData(
    0xe9e5,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tdm = IconData(
    0xe9e6,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pio = IconData(
    0xe9e7,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData drc = IconData(
    0xe9e8,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData drc_rarity = IconData(
    0xe9e9,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData drc_border = IconData(
    0xe9ea,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData drc_inner = IconData(
    0xe9eb,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tdm_border = IconData(
    0xe9ec,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData fin = IconData(
    0xe9ed,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData fin_rarity = IconData(
    0xe9ee,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData fin_border = IconData(
    0xe9ef,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData eoe = IconData(
    0xe9f0,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData spm = IconData(
    0xe9f1,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData spm_inner = IconData(
    0xe9f2,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData spe = IconData(
    0xe9f3,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tdc = IconData(
    0xe9f4,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData fic = IconData(
    0xe9f5,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData eoc = IconData(
    0xe9f6,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData eoc_inner = IconData(
    0xe9f7,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData fca = IconData(
    0xe9f8,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mar = IconData(
    0xe9f9,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mar_inner = IconData(
    0xe9fa,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tla = IconData(
    0xe9fb,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sta_jpn = IconData(
    0xe9fc,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tla_border = IconData(
    0xe9fd,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tla_inner = IconData(
    0xe9fe,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData eos = IconData(
    0xe9ff,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData eos_border = IconData(
    0xea00,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pma = IconData(
    0xea01,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pm2 = IconData(
    0xea02,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dvk = IconData(
    0xea03,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ecl = IconData(
    0xea04,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ecl_border = IconData(
    0xea05,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tmt = IconData(
    0xea06,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tmt_border = IconData(
    0xea07,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pza = IconData(
    0xea08,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pza_border = IconData(
    0xea09,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tle_rarity = IconData(
    0xea0a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tle_border = IconData(
    0xea0b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tle_inner = IconData(
    0xea0c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData om1_rarity = IconData(
    0xea0d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData om1 = IconData(
    0xea0e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData omb_rarity = IconData(
    0xea0f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData omb = IconData(
    0xea10,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ecc = IconData(
    0xea11,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ecc_rarity = IconData(
    0xea12,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ecc_border = IconData(
    0xea13,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ecc_inner = IconData(
    0xea14,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tmc = IconData(
    0xea15,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tmc_border = IconData(
    0xea16,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tmt_inner = IconData(
    0xea17,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
}
