/// Flutter icons ManaIcons
/// Copyright (C) two019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ManaIcons
///      fonts:
///       - asset: fonts/ManaIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Keyrune {

  static const _kFontFam = 'Keyrune';

  static const Map<String, IconData> sets = <String,IconData>{
    "eld": eld,
    "c19": c19,
    "tc19": c19,
    "ps19": pmtg1,
    "pm20": m20,
    "tm20": m20,
    "ppp1": m20,
    "m20": m20,
    "ss2": ss2,
    "pmh1": mh1,
    "mh1": mh1,
    "tmh1": mh1,
    "pwar": war,
    "twar": war,
    "war": war,
    "j19": parl,
    "prw2": rna,
    "prna": rna,
    "rna": rna,
    "trna": rna,
    "puma": uma,
    "uma": uma,
    "tuma": uma,
    "gnt": gnt,
    "opca": pca,
    "grn": grn,
    "med": med,
    "oc18": c18,
    "c18": c18,
    // "htr17": htr,
    // "ana": "Arena New Player Experience",
    "m19": m19,
    "gs1": gs1,
    "ss1": ss1,
    "cm2": cm2,
    "bbd": bbd,
    "dom": dom, //Dominaria
    "ddu": ddu,
    "a25": a25,
    "rix": rix, //Rivals of ixalan
    "ust": ust,
    // "htr17": htr17, //2017 Heroes of the Realm
    // "ana": ana, //Arena New Player Experience
    // "gs1": , //Global Series Jiang Yanggu & Mu Yanling
    "v17": v17, //From the Vault: Transform
    "ima": ima, //Iconic Masters
    "ddt": ddt, //Duel Decks: Merfolk vs. Goblins
    "xln": xln, //Ixalan
    "h17": h17, //HasCon 2017
    // "htr": htr, //2016 Heroes of the Realm
    "oc17": c17, //Commander 2017 Oversized
    "c17": c17, //Commander 2017
    "hou": hou, //Hour of Devastation
    // "oe01": oe01, //Archenemy: Nicol Bolas Schemes
    "e01": e01, //Archenemy: Nicol Bolas
    "cma": cma, //Commander Anthology
    "akh": akh, //Amonkhet
    "mp2": mp2, //Amonkhet Invocations
    "w17": w17, //Welcome Deck 2017
    "dds": dds, //Duel Decks: Mind vs. Might
    "mm3": mm3, //Modern Masters 2017
    "aer": aer, //Aether Revolt
    "pca": pca, //Planechase Anthology
    "oc16": c16, //Commander 2016 Oversized
    "c16": c16, //Commander 2016
    "kld": kld, //Kaladesh
    "mps": kld, //Kaladesh Inventions
    "ddr": ddr, //Duel Decks: Nissa vs. Ob Nixilis
    "cn2": cn2, //Conspiracy: Take the Crown
    "v16": v16, //From the Vault: Lore
    "emn": emn, //Eldritch Moon
    "ema": ema, //Eternal Masters
    "soi": soi, //Shadows over Innistrad
    "w16": w16, //Welcome Deck 2016
    "ddq": ddq, //Duel Decks: Blessed vs. Cursed
    "ogw": ogw, //Oath of the Gatewatch
    "oc15": c15, //Commander 2015 Oversized
    "c15": c15, //Commander 2015
    "bfz": bfz, //Battle for Zendikar
    "exp": exp, //Zendikar Expeditions
    "ddp": ddp, //Duel Decks: Zendikar vs. Eldrazi
    "v15": v15, //From the Vault: Angels
    "cp3": ori, //Magic Origins Clash Pack
    "ori": ori, //Magic Origins
    "mm2": mm2, //Modern Masters 2015
    "tpr": tpr, //Tempest Remastered
    "dtk": dtk, //Dragons of Tarkir
    "ddo": ddo, //Duel Decks: Elspeth vs. Kiora
    "cp2": frf, //Fate Reforged Clash Pack
    "frf": frf, //Fate Reforged
    "dvd": ddd, //Duel Decks Anthology: Divine vs. Demonic
    "gvl": ddg, //Duel Decks Anthology: Garruk vs. Liliana
    "evg": evg, //Duel Decks Anthology: Elves vs. Goblins
    "jvc": ddj, //Duel Decks Anthology: Jace vs. Chandra
    "oc14": c14, //Commander 2014 Oversized
    "c14": c14, //Commander 2014
    "ktk": ktk, //Khans of Tarkir
    "ddn": ddn, //Duel Decks: Speed vs. Cunning
    "v14": v14, //From the Vault: Annihilation
    "m15": m15, //Magic 2015
    "cp1": m15, //Magic 2015 Clash Pack
    "ppc1": m15, //M15 Prerelease Challenge
    "vma": vma, //Vintage Masters
    "cns": cns, //Conspiracy
    "jou": jou, //Journey into Nyx
    "ddm": ddm, //Duel Decks: Jace vs. Vraska
    "bng": bng, //Born of the Gods
    "oc13": c13, //Commander 2013 Oversized
    "c13": c13, //Commander 2013
    "ths": ths, //Theros
    "ddl": ddl, //Duel Decks: Heroes vs. Monsters
    "v13": v13, //From the Vault: Twenty
    "m14": m14, //Magic 2014
    "mma": mma, //Modern Masters
    "dgm": dgm, //Dragon's Maze
    "ddk": ddk, //Duel Decks: Sorin vs. Tibalt
    "gtc": gtc, //Gatecrash
    // "ocm1": ocm1, //Commander's Arsenal Oversized
    "cm1": cm1, //Commander's Arsenal
    "rtr": rtr, //Return to Ravnica
    "ddj": ddj, //Duel Decks: Izzet vs. Golgari
    "v12": v12, //From the Vault: Realms
    "m13": m13, //Magic 2013
    // "opc2": opc2, //Planechase 2012 Planes
    "pc2": pc2, //Planechase 2012
    "avr": avr, //Avacyn Restored
    // "phel": phel, //Open the Helvault
    "ddi": ddi, //Duel Decks: Venser vs. Koth
    "dka": dka, //Dark Ascension
    "pd3": pd3, //Premium Deck Series: Graveborn
    "isd": isd, //Innistrad
    "ddh": ddh, //Duel Decks: Ajani vs. Nicol Bolas
    "v11": v11, //From the Vault: Legends
    "m12": m12, //Magic 2012
    "ocmd": cmd, //Commander 2011 Oversized
    "pcmd": cmd, //Commander 2011 Launch Party
    "cmd": cmd, //Commander 2011
    "td2": td2, //Duel Decks: Mirrodin Pure vs. New Phyrexia
    "nph": nph, //New Phyrexia
    "ddg": ddg, //Duel Decks: Knights vs. Dragons
    "mbs": mbs, //Mirrodin Besieged
    "me4": me4, //Masters Edition IV
    // "olgc": olgc, //Legacy Championship
    "pd2": pd2, //Premium Deck Series: Fire and Lightning
    "som": som, //Scars of Mirrodin
    "ddf": ddf, //Duel Decks: Elspeth vs. Tezzeret
    "v10": v10, //From the Vault: Relics
    "m11": m11, //Magic 2011
    // "oarc": oarc, //Archenemy Schemes
    // "arc": arc, //Archenemy
    // "parc": parc, //Promotional Schemes
    "roe": roe, //Rise of the Eldrazi
    "dde": dde, //Duel Decks: Phyrexia vs. the Coalition
    "wwk": wwk, //Worldwake
    "h09": h09, //Premium Deck Series: Slivers
    "ddd": ddd, //Duel Decks: Garruk vs. Liliana
    "zen": zen, //Zendikar
    "me3": me3, //Masters Edition III
    // "ohop": ohop, //Planechase Planes
    "hop": hop, //Planechase
    "v09": v09, //From the Vault: Exiled
    "m10": m10, //Magic 2010
    "arb": arb, //Alara Reborn
    "ddc": ddc, //Duel Decks: Divine vs. Demonic
    "con": con, //Conflux
    "dd2": dd2, //Duel Decks: Jace vs. Chandra
    "ala": ala, //Shards of Alara
    "me2": me2, //Masters Edition II
    "drb": drb, //From the Vault: Dragons
    "eve": eve, //Eventide
    "shm": shm, //Shadowmoor
    "mor": mor, //Morningtide
    // "dd1": dd1, //Duel Decks: Elves vs. Goblins
    "lrw": lrw, //Lorwyn
    "me1": me1, //Masters Edition
    "10e": ten_ed, //Tenth Edition
    "fut": fut, //Future Sight
    "plc": plc, //Planar Chaos
    // "hho": hho, //Happy Holidays
    "tsp": tsp, //Time Spiral
    "tsb": tsp, //Time Spiral Timeshifted
    "csp": csp, //Coldsnap
    "dis": dis, //Dissension
    "gpt": gpt, //Guildpact
    "rav": rav, //Ravnica: City of Guilds
    "9ed": nine_ed, //Ninth Edition
    "sok": sok, //Saviors of Kamigawa
    "bok": bok, //Betrayers of Kamigawa
    "unh": unh, //Unhinged
    "chk": chk, //Champions of Kamigawa
    // "wc04": wc04, //World Championship Decks 2004
    "5dn": five_dn, //Fifth Dawn
    "dst": dst, //Darksteel
    "mrd": mrd, //Mirrodin
    // "wc03": wc03, //World Championship Decks 2003
    "8ed": eigth_ed, //Eighth Edition
    "scg": scg, //Scourge
    "lgn": lgn, //Legions
    // "ovnt": ovnt, //Vintage Championship
    "ons": ons, //Onslaught
    // "wc02": wc02, //World Championship Decks 2002
    "jud": jud, //Judgment
    "tor": tor, //Torment
    "ody": ody, //Odyssey
    // "wc01": wc01, //World Championship Decks 2001
    "apc": apc, //Apocalypse
    "7ed": seven_ed, //Seventh Edition
    "pls": pls, //Planeshift
    "inv": inv, //Invasion
    // "wc00": wc00, //World Championship Decks 2000
    "pcy": pcy, //Prophecy
    "s00": s00, //Starter 2000
    // "nem": nem, //Nemesis
    "mmq": mmq, //Mercadian Masques
    // "wc99": wc99, //World Championship Decks 1999
    "s99": s99, //Starter 1999
    "uds": uds, //Urza's Destiny
    "ptk": ptk, //Portal Three Kingdoms
    "6ed": six_ed, //Classic Sixth Edition
    "ulg": ulg, //Urza's Legacy
    "usg": usg, //Urza's Saga
    // "wc98": wc98, //World Championship Decks 1998
    "ugl": ugl, //Unglued
    "exo": exo, //Exodus
    // "p02": p02, //Portal Second Age
    "sth": sth, //Stronghold
    "tmp": tmp, //Tempest
    // "wc97": wc97, //World Championship Decks 1997
    "wth": wth, //Weatherlight
    "por": por, //Portal
    // "ppod": ppod, //Portal Demo Game
    "5ed": five_ed, //Fifth Edition
    "vis": vis, //Visions
    // "itp": itp, //Introductory Two-Player Set
    "mir": mir, //Mirage
    // "pcel": pcel, //Celebration Cards
    "all": all, //Alliances
    // "ptc": ptc, //Pro Tour Collector Set
    "hml": hml, //Homelands
    // "rin": rin, //Rinascimento
    // "ren": ren, //Renaissance
    "chr": chr, //Chronicles
    "ice": ice, //Ice Age
    "4bb": four_ed, //Fourth Edition Foreign Black Border
    "4ed": four_ed, //Fourth Edition
    "fem": fem, //Fallen Empires
    "drk": drk, //The Dark
    // "sum": sum, //Summer Magic / Edgar
    "leg": leg, //Legends
    // "3ed": 3ed, //Revised Edition
    // "fbb": fbb, //Foreign Black Border
    "atq": atq, //Antiquities
    "arn": arn, //Arabian Nights
    // "cei": cei, //Intl. Collectors’ Edition
    // "ced": ced, //Collectors’ Edition
    // "2ed": 2ed, //Unlimited Edition
    "leb": leb, //Limited Edition Beta
    "lea": lea, //Limited Edition Alpha  
  };

  static const IconData lea = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData leb = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData two_ed = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData three_ed = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData four_ed = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData psum = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData five_ed = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData six_ed = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData seven_ed = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData eigth_ed = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData nine_ed = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData ten_ed = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData m10 = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData m11 = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData m12 = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData m13 = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData m14 = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData m15 = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData bcore = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData arn = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData atq = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData leg = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData drk = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData fem = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData hml = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData ice = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData all = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData csp = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData mir = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData vis = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData wth = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData tmp = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData sth = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData exo = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData usg = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData ulg = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData uds = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData mmq = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData nms__nem = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData pcy = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData inv = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData pls = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData apc = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData ody = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData tor = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData jud = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData ons = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData lgn = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData scg = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData mrd = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData dst = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData five_dn = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData chk = const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData bok = const IconData(0xe835, fontFamily: _kFontFam);
  static const IconData sok = const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData rav = const IconData(0xe837, fontFamily: _kFontFam);
  static const IconData gpt = const IconData(0xe838, fontFamily: _kFontFam);
  static const IconData dis = const IconData(0xe839, fontFamily: _kFontFam);
  static const IconData tsp = const IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData plc = const IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData fut = const IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData lrw = const IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData mor = const IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData shm = const IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData eve = const IconData(0xe840, fontFamily: _kFontFam);
  static const IconData ala = const IconData(0xe841, fontFamily: _kFontFam);
  static const IconData con = const IconData(0xe842, fontFamily: _kFontFam);
  static const IconData arb = const IconData(0xe843, fontFamily: _kFontFam);
  static const IconData zen = const IconData(0xe844, fontFamily: _kFontFam);
  static const IconData wwk = const IconData(0xe845, fontFamily: _kFontFam);
  static const IconData roe = const IconData(0xe846, fontFamily: _kFontFam);
  static const IconData som = const IconData(0xe847, fontFamily: _kFontFam);
  static const IconData mbs = const IconData(0xe848, fontFamily: _kFontFam);
  static const IconData nph = const IconData(0xe849, fontFamily: _kFontFam);
  static const IconData isd = const IconData(0xe84a, fontFamily: _kFontFam);
  static const IconData dka = const IconData(0xe84b, fontFamily: _kFontFam);
  static const IconData avr = const IconData(0xe84c, fontFamily: _kFontFam);
  static const IconData rtr = const IconData(0xe84d, fontFamily: _kFontFam);
  static const IconData gtc = const IconData(0xe84e, fontFamily: _kFontFam);
  static const IconData dgm = const IconData(0xe84f, fontFamily: _kFontFam);
  static const IconData ths = const IconData(0xe850, fontFamily: _kFontFam);
  static const IconData bng = const IconData(0xe851, fontFamily: _kFontFam);
  static const IconData jou = const IconData(0xe852, fontFamily: _kFontFam);
  static const IconData ktk = const IconData(0xe853, fontFamily: _kFontFam);
  static const IconData frf = const IconData(0xe854, fontFamily: _kFontFam);
  static const IconData van = const IconData(0xe855, fontFamily: _kFontFam);
  static const IconData hop = const IconData(0xe856, fontFamily: _kFontFam);
  static const IconData arc__ann = const IconData(0xe857, fontFamily: _kFontFam);
  static const IconData cmd = const IconData(0xe858, fontFamily: _kFontFam);
  static const IconData pc2 = const IconData(0xe859, fontFamily: _kFontFam);
  static const IconData cm1 = const IconData(0xe85a, fontFamily: _kFontFam);
  static const IconData c13 = const IconData(0xe85b, fontFamily: _kFontFam);
  static const IconData cns = const IconData(0xe85c, fontFamily: _kFontFam);
  static const IconData c14 = const IconData(0xe85d, fontFamily: _kFontFam);
  static const IconData chr = const IconData(0xe85e, fontFamily: _kFontFam);
  static const IconData ath = const IconData(0xe85f, fontFamily: _kFontFam);
  static const IconData brb = const IconData(0xe860, fontFamily: _kFontFam);
  static const IconData btd = const IconData(0xe861, fontFamily: _kFontFam);
  static const IconData dkm = const IconData(0xe862, fontFamily: _kFontFam);
  static const IconData mma = const IconData(0xe863, fontFamily: _kFontFam);
  static const IconData por = const IconData(0xe864, fontFamily: _kFontFam);
  static const IconData po2 = const IconData(0xe865, fontFamily: _kFontFam);
  static const IconData ptk = const IconData(0xe866, fontFamily: _kFontFam);
  static const IconData s99 = const IconData(0xe867, fontFamily: _kFontFam);
  static const IconData s00 = const IconData(0xe868, fontFamily: _kFontFam);
  static const IconData evg = const IconData(0xe869, fontFamily: _kFontFam);
  static const IconData dd2 = const IconData(0xe86a, fontFamily: _kFontFam);
  static const IconData ddc = const IconData(0xe86b, fontFamily: _kFontFam);
  static const IconData ddd = const IconData(0xe86c, fontFamily: _kFontFam);
  static const IconData dde = const IconData(0xe86d, fontFamily: _kFontFam);
  static const IconData ddf = const IconData(0xe86e, fontFamily: _kFontFam);
  static const IconData ddg = const IconData(0xe86f, fontFamily: _kFontFam);
  static const IconData ddh = const IconData(0xe870, fontFamily: _kFontFam);
  static const IconData ddi = const IconData(0xe871, fontFamily: _kFontFam);
  static const IconData ddj = const IconData(0xe872, fontFamily: _kFontFam);
  static const IconData ddk = const IconData(0xe873, fontFamily: _kFontFam);
  static const IconData ddl = const IconData(0xe874, fontFamily: _kFontFam);
  static const IconData ddm = const IconData(0xe875, fontFamily: _kFontFam);
  static const IconData ddn = const IconData(0xe876, fontFamily: _kFontFam);
  static const IconData ddo = const IconData(0xe877, fontFamily: _kFontFam);
  static const IconData drb = const IconData(0xe878, fontFamily: _kFontFam);
  static const IconData v09 = const IconData(0xe879, fontFamily: _kFontFam);
  static const IconData v10 = const IconData(0xe87a, fontFamily: _kFontFam);
  static const IconData v11 = const IconData(0xe87b, fontFamily: _kFontFam);
  static const IconData v12 = const IconData(0xe87c, fontFamily: _kFontFam);
  static const IconData v13 = const IconData(0xe87d, fontFamily: _kFontFam);
  static const IconData v14 = const IconData(0xe87e, fontFamily: _kFontFam);
  static const IconData h09 = const IconData(0xe87f, fontFamily: _kFontFam);
  static const IconData pd2 = const IconData(0xe880, fontFamily: _kFontFam);
  static const IconData pd3 = const IconData(0xe881, fontFamily: _kFontFam);
  static const IconData md1 = const IconData(0xe882, fontFamily: _kFontFam);
  static const IconData pgru = const IconData(0xe883, fontFamily: _kFontFam);
  static const IconData pmtg1 = const IconData(0xe884, fontFamily: _kFontFam);
  static const IconData pmtg2 = const IconData(0xe885, fontFamily: _kFontFam);
  static const IconData pleaf = const IconData(0xe886, fontFamily: _kFontFam);
  static const IconData pmei = const IconData(0xe887, fontFamily: _kFontFam);
  static const IconData parl = const IconData(0xe888, fontFamily: _kFontFam);
  static const IconData dpa = const IconData(0xe889, fontFamily: _kFontFam);
  static const IconData pbook = const IconData(0xe88a, fontFamily: _kFontFam);
  static const IconData past = const IconData(0xe88b, fontFamily: _kFontFam);
  static const IconData parl2 = const IconData(0xe88c, fontFamily: _kFontFam);
  static const IconData me1 = const IconData(0xe88d, fontFamily: _kFontFam);
  static const IconData me2 = const IconData(0xe88e, fontFamily: _kFontFam);
  static const IconData me3 = const IconData(0xe88f, fontFamily: _kFontFam);
  static const IconData me4 = const IconData(0xe890, fontFamily: _kFontFam);
  static const IconData ugl = const IconData(0xe891, fontFamily: _kFontFam);
  static const IconData unh = const IconData(0xe892, fontFamily: _kFontFam);
  static const IconData dtk = const IconData(0xe893, fontFamily: _kFontFam);
  static const IconData tpr = const IconData(0xe894, fontFamily: _kFontFam);
  static const IconData mm2 = const IconData(0xe895, fontFamily: _kFontFam);
  static const IconData vma = const IconData(0xe896, fontFamily: _kFontFam);
  static const IconData ori = const IconData(0xe897, fontFamily: _kFontFam);
  static const IconData ddp = const IconData(0xe898, fontFamily: _kFontFam);
  static const IconData bfz = const IconData(0xe899, fontFamily: _kFontFam);
  static const IconData exp = const IconData(0xe89a, fontFamily: _kFontFam);
  static const IconData c15 = const IconData(0xe900, fontFamily: _kFontFam);
  static const IconData ogw = const IconData(0xe901, fontFamily: _kFontFam);
  static const IconData soi = const IconData(0xe902, fontFamily: _kFontFam);
  static const IconData ema = const IconData(0xe903, fontFamily: _kFontFam);
  static const IconData cn2 = const IconData(0xe904, fontFamily: _kFontFam);
  static const IconData v15 = const IconData(0xe905, fontFamily: _kFontFam);
  static const IconData v16 = const IconData(0xe906, fontFamily: _kFontFam);
  static const IconData w16 = const IconData(0xe907, fontFamily: _kFontFam);
  static const IconData ddq = const IconData(0xe908, fontFamily: _kFontFam);
  static const IconData psalvat05 = const IconData(0xe909, fontFamily: _kFontFam);
  static const IconData psalvat11 = const IconData(0xe90a, fontFamily: _kFontFam);
  static const IconData emn = const IconData(0xe90b, fontFamily: _kFontFam);
  static const IconData xlcu__pz1 = const IconData(0xe90c, fontFamily: _kFontFam);
  static const IconData ddr = const IconData(0xe90d, fontFamily: _kFontFam);
  static const IconData kld = const IconData(0xe90e, fontFamily: _kFontFam);
  static const IconData aer = const IconData(0xe90f, fontFamily: _kFontFam);
  static const IconData c16 = const IconData(0xe910, fontFamily: _kFontFam);
  static const IconData pca = const IconData(0xe911, fontFamily: _kFontFam);
  static const IconData mm3 = const IconData(0xe912, fontFamily: _kFontFam);
  static const IconData mp1 = const IconData(0xe913, fontFamily: _kFontFam);
  static const IconData akh = const IconData(0xe914, fontFamily: _kFontFam);
  static const IconData pxbox = const IconData(0xe915, fontFamily: _kFontFam);
  static const IconData cma = const IconData(0xe916, fontFamily: _kFontFam);
  static const IconData xren = const IconData(0xe917, fontFamily: _kFontFam);
  static const IconData xrin = const IconData(0xe918, fontFamily: _kFontFam);
  static const IconData pmps = const IconData(0xe919, fontFamily: _kFontFam);
  static const IconData pmpu = const IconData(0xe91a, fontFamily: _kFontFam);
  static const IconData pmodo = const IconData(0xe91b, fontFamily: _kFontFam);
  static const IconData td2 = const IconData(0xe91c, fontFamily: _kFontFam);
  static const IconData xduels = const IconData(0xe91d, fontFamily: _kFontFam);
  static const IconData xmods = const IconData(0xe91e, fontFamily: _kFontFam);
  static const IconData pz2__pmotc = const IconData(0xe91f, fontFamily: _kFontFam);
  static const IconData v0x = const IconData(0xe920, fontFamily: _kFontFam);
  static const IconData dds = const IconData(0xe921, fontFamily: _kFontFam);
  static const IconData mp2 = const IconData(0xe922, fontFamily: _kFontFam);
  static const IconData w17 = const IconData(0xe923, fontFamily: _kFontFam);
  static const IconData hou = const IconData(0xe924, fontFamily: _kFontFam);
  static const IconData ice2 = const IconData(0xe925, fontFamily: _kFontFam);
  static const IconData xcle = const IconData(0xe926, fontFamily: _kFontFam);
  static const IconData xice = const IconData(0xe927, fontFamily: _kFontFam);
  static const IconData x2ps = const IconData(0xe928, fontFamily: _kFontFam);
  static const IconData x4ea = const IconData(0xe929, fontFamily: _kFontFam);
  static const IconData papac = const IconData(0xe92a, fontFamily: _kFontFam);
  static const IconData peuro = const IconData(0xe92b, fontFamily: _kFontFam);
  static const IconData pidw = const IconData(0xe92c, fontFamily: _kFontFam);
  static const IconData e01 = const IconData(0xe92d, fontFamily: _kFontFam);
  static const IconData xln = const IconData(0xe92e, fontFamily: _kFontFam);
  static const IconData rix = const IconData(0xe92f, fontFamily: _kFontFam);
  static const IconData ust = const IconData(0xe930, fontFamily: _kFontFam);
  static const IconData e02 = const IconData(0xe931, fontFamily: _kFontFam);
  static const IconData pdgc = const IconData(0xe932, fontFamily: _kFontFam);
  static const IconData ddt = const IconData(0xe933, fontFamily: _kFontFam);
  static const IconData c17 = const IconData(0xe934, fontFamily: _kFontFam);
  static const IconData ima = const IconData(0xe935, fontFamily: _kFontFam);
  static const IconData pheart = const IconData(0xe936, fontFamily: _kFontFam);
  static const IconData pfnm = const IconData(0xe937, fontFamily: _kFontFam);
  static const IconData h17 = const IconData(0xe938, fontFamily: _kFontFam);
  static const IconData v17 = const IconData(0xe939, fontFamily: _kFontFam);
  static const IconData pdep = const IconData(0xe93a, fontFamily: _kFontFam);
  static const IconData psega = const IconData(0xe93b, fontFamily: _kFontFam);
  static const IconData ptsa = const IconData(0xe93c, fontFamily: _kFontFam);
  static const IconData a25 = const IconData(0xe93d, fontFamily: _kFontFam);
  static const IconData ddu = const IconData(0xe93e, fontFamily: _kFontFam);
  static const IconData dom = const IconData(0xe93f, fontFamily: _kFontFam);
  static const IconData cm2 = const IconData(0xe940, fontFamily: _kFontFam);
  static const IconData m19 = const IconData(0xe941, fontFamily: _kFontFam);
  static const IconData bbd = const IconData(0xe942, fontFamily: _kFontFam);
  static const IconData parl3 = const IconData(0xe943, fontFamily: _kFontFam);
  static const IconData ss1 = const IconData(0xe944, fontFamily: _kFontFam);
  static const IconData gs1 = const IconData(0xe945, fontFamily: _kFontFam);
  static const IconData c18 = const IconData(0xe946, fontFamily: _kFontFam);
  static const IconData x1e = const IconData(0xe947, fontFamily: _kFontFam);
  static const IconData x2e = const IconData(0xe948, fontFamily: _kFontFam);
  static const IconData x2u = const IconData(0xe949, fontFamily: _kFontFam);
  static const IconData x3e = const IconData(0xe94a, fontFamily: _kFontFam);
  static const IconData grn = const IconData(0xe94b, fontFamily: _kFontFam);
  static const IconData med = const IconData(0xe94c, fontFamily: _kFontFam);
  static const IconData gnt = const IconData(0xe94d, fontFamily: _kFontFam);
  static const IconData azorius = const IconData(0xe94e, fontFamily: _kFontFam);
  static const IconData boros = const IconData(0xe94f, fontFamily: _kFontFam);
  static const IconData dimir = const IconData(0xe950, fontFamily: _kFontFam);
  static const IconData golgari = const IconData(0xe951, fontFamily: _kFontFam);
  static const IconData gruul = const IconData(0xe952, fontFamily: _kFontFam);
  static const IconData izzet = const IconData(0xe953, fontFamily: _kFontFam);
  static const IconData orzhov = const IconData(0xe954, fontFamily: _kFontFam);
  static const IconData rakdos = const IconData(0xe955, fontFamily: _kFontFam);
  static const IconData selesnya = const IconData(0xe956, fontFamily: _kFontFam);
  static const IconData simic = const IconData(0xe957, fontFamily: _kFontFam);
  static const IconData uma = const IconData(0xe958, fontFamily: _kFontFam);
  static const IconData rna = const IconData(0xe959, fontFamily: _kFontFam);
  static const IconData war = const IconData(0xe95a, fontFamily: _kFontFam);
  static const IconData mh1 = const IconData(0xe95b, fontFamily: _kFontFam);
  static const IconData ss2 = const IconData(0xe95c, fontFamily: _kFontFam);
  static const IconData m20 = const IconData(0xe95d, fontFamily: _kFontFam);
  static const IconData eld = const IconData(0xe95e, fontFamily: _kFontFam);
  static const IconData c19 = const IconData(0xe95f, fontFamily: _kFontFam);
}
