// ignore_for_file: constant_identifier_names

import 'package:flutter/material.dart';

/// Flutter icons ManaIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ManaIcons
///      fonts:
///       - asset: fonts/ManaIcons.ttf
///
/// 
///


class ManaIcons {
  ManaIcons._();

  static Map<String,IconData> basicTypes = <String, IconData>{
    "Creature": creature,
    "Sorcery": sorcery,
    "Instant": instant,
    "Enchantment": enchantment,
    "Land": land,
    "Planeswalker": planeswalker,
    "Artifact": artifact,
  };



  static const Map<int,IconData> numbers = {
    0: zero,
    1: one,
    2: two,
    3: three,
    4: four,
    5: five,
    6: six,
    7: seven,
    8: eight,
    9: nine,
    10: ten,
    11: eleven,
    12: twelve,
    13: thirteen,
    14: fourteen,
    15: fifteen,
    16: sixteen,
    17: seventeen,
    18: eighteen,
    19: nineteen,
    20: twenty,
    100: hundred,
    1000000: million,
  };

  static const _kFontFam = 'ManaIcons';

  static const IconData zero = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData one = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData two = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData three = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData four = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData five = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData six = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData seven = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData eight = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData nine = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData ten = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData eleven = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData twelve = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData thirteen = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData fourteen = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData fifteen = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData sixteen = IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData seventeen = IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData eighteen = IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData nineteen = IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData twenty = IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData hundred = IconData(0xe900, fontFamily: _kFontFam);
  static const IconData million = IconData(0xe901, fontFamily: _kFontFam);

  static const IconData w = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData u = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData b = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData r = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData g = IconData(0xe804, fontFamily: _kFontFam);

  static const IconData c = IconData(0xe904, fontFamily: _kFontFam);

  static const IconData x = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData y = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData z = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData p = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData s = IconData(0xe819, fontFamily: _kFontFam);

  static const IconData tap = IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData untap = IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData tap_alt = IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData chaos = IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData artifact = IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData creature = IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData enchantment = IconData(0xe820, fontFamily: _kFontFam);
  static const IconData instant = IconData(0xe821, fontFamily: _kFontFam);
  static const IconData land = IconData(0xe822, fontFamily: _kFontFam);
  static const IconData planeswalker = IconData(0xe823, fontFamily: _kFontFam);
  static const IconData sorcery = IconData(0xe824, fontFamily: _kFontFam);
  static const IconData loyalty_down = IconData(0xe825, fontFamily: _kFontFam);
  static const IconData loyalty_zero = IconData(0xe826, fontFamily: _kFontFam);
  static const IconData loyalty_up = IconData(0xe827, fontFamily: _kFontFam);
  static const IconData loyalty_start = IconData(0xe828, fontFamily: _kFontFam);
  static const IconData flashback = IconData(0xe829, fontFamily: _kFontFam);
  static const IconData half = IconData(0xe902, fontFamily: _kFontFam);
  static const IconData infinity = IconData(0xe903, fontFamily: _kFontFam);
  static const IconData dfc_night = IconData(0xe905, fontFamily: _kFontFam);
  static const IconData dfc_day = IconData(0xe906, fontFamily: _kFontFam);
  static const IconData e = IconData(0xe907, fontFamily: _kFontFam);
  static const IconData dfc_ignite = IconData(0xe908, fontFamily: _kFontFam);
  static const IconData dfc_spark = IconData(0xe909, fontFamily: _kFontFam);
  static const IconData dfc_emrakul = IconData(0xe90a, fontFamily: _kFontFam);
  static const IconData dfc_moon = IconData(0xe90b, fontFamily: _kFontFam);
  static const IconData guild_azorius = IconData(0xe90c, fontFamily: _kFontFam);
  static const IconData guild_boros = IconData(0xe90d, fontFamily: _kFontFam);
  static const IconData guild_dimir = IconData(0xe90e, fontFamily: _kFontFam);
  static const IconData guild_golgari = IconData(0xe90f, fontFamily: _kFontFam);
  static const IconData guild_gruul = IconData(0xe910, fontFamily: _kFontFam);
  static const IconData guild_izzet = IconData(0xe911, fontFamily: _kFontFam);
  static const IconData guild_orzhov = IconData(0xe912, fontFamily: _kFontFam);
  static const IconData guild_rakdos = IconData(0xe913, fontFamily: _kFontFam);
  static const IconData guild_selesnya = IconData(0xe914, fontFamily: _kFontFam);
  static const IconData guild_simic = IconData(0xe915, fontFamily: _kFontFam);
  static const IconData clan_abzan = IconData(0xe916, fontFamily: _kFontFam);
  static const IconData clan_jeskai = IconData(0xe917, fontFamily: _kFontFam);
  static const IconData clan_mardu = IconData(0xe918, fontFamily: _kFontFam);
  static const IconData clan_sultai = IconData(0xe919, fontFamily: _kFontFam);
  static const IconData clan_temur = IconData(0xe91a, fontFamily: _kFontFam);
  static const IconData clan_atarka = IconData(0xe91b, fontFamily: _kFontFam);
  static const IconData clan_dromoka = IconData(0xe91c, fontFamily: _kFontFam);
  static const IconData clan_kolaghan = IconData(0xe91d, fontFamily: _kFontFam);
  static const IconData clan_ojutai = IconData(0xe91e, fontFamily: _kFontFam);
  static const IconData clan_silumgar = IconData(0xe91f, fontFamily: _kFontFam);
  static const IconData dfc_enchantment = IconData(0xe920, fontFamily: _kFontFam);
  static const IconData power = IconData(0xe921, fontFamily: _kFontFam);
  static const IconData toughness = IconData(0xe922, fontFamily: _kFontFam);
  static const IconData artist_brush = IconData(0xe923, fontFamily: _kFontFam);
  static const IconData artist_nib = IconData(0xe924, fontFamily: _kFontFam);
  static const IconData multiple = IconData(0xe925, fontFamily: _kFontFam);
  static const IconData polis_setessa = IconData(0xe926, fontFamily: _kFontFam);
  static const IconData polis_akros = IconData(0xe927, fontFamily: _kFontFam);
  static const IconData polis_meletis = IconData(0xe928, fontFamily: _kFontFam);
}
