import 'package:flutter/material.dart';

/// Flutter icons ManaIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ManaIcons
///      fonts:
///       - asset: fonts/ManaIcons.ttf
///
/// 
///


class ManaIcons {
  ManaIcons._();

  static Map<String,IconData> basicTypes = <String, IconData>{
    "Creature": creature,
    "Sorcery": sorcery,
    "Instant": instant,
    "Enchantment": enchantment,
    "Land": land,
    "Planeswalker": planeswalker,
    "Artifact": artifact,
  };



  static const Map<int,IconData> numbers = {
    0: zero,
    1: one,
    2: two,
    3: three,
    4: four,
    5: five,
    6: six,
    7: seven,
    8: eight,
    9: nine,
    10: ten,
    11: eleven,
    12: twelve,
    13: thirteen,
    14: fourteen,
    15: fifteen,
    16: sixteen,
    17: seventeen,
    18: eighteen,
    19: nineteen,
    20: twenty,
    100: hundred,
    1000000: million,
  };

  static const _kFontFam = 'ManaIcons';

  static const IconData zero = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData one = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData two = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData three = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData four = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData five = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData six = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData seven = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData eight = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData nine = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData ten = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData eleven = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData twelve = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData thirteen = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData fourteen = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData fifteen = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData sixteen = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData seventeen = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData eighteen = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData nineteen = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData twenty = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData hundred = const IconData(0xe900, fontFamily: _kFontFam);
  static const IconData million = const IconData(0xe901, fontFamily: _kFontFam);

  static const IconData w = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData u = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData b = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData r = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData g = const IconData(0xe804, fontFamily: _kFontFam);

  static const IconData c = const IconData(0xe904, fontFamily: _kFontFam);

  static const IconData x = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData y = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData z = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData p = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData s = const IconData(0xe819, fontFamily: _kFontFam);

  static const IconData tap = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData untap = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData tap_alt = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData chaos = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData artifact = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData creature = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData enchantment = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData instant = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData land = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData planeswalker = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData sorcery = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData loyalty_down = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData loyalty_zero = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData loyalty_up = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData loyalty_start = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData flashback = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData half = const IconData(0xe902, fontFamily: _kFontFam);
  static const IconData infinity = const IconData(0xe903, fontFamily: _kFontFam);
  static const IconData dfc_night = const IconData(0xe905, fontFamily: _kFontFam);
  static const IconData dfc_day = const IconData(0xe906, fontFamily: _kFontFam);
  static const IconData e = const IconData(0xe907, fontFamily: _kFontFam);
  static const IconData dfc_ignite = const IconData(0xe908, fontFamily: _kFontFam);
  static const IconData dfc_spark = const IconData(0xe909, fontFamily: _kFontFam);
  static const IconData dfc_emrakul = const IconData(0xe90a, fontFamily: _kFontFam);
  static const IconData dfc_moon = const IconData(0xe90b, fontFamily: _kFontFam);
  static const IconData guild_azorius = const IconData(0xe90c, fontFamily: _kFontFam);
  static const IconData guild_boros = const IconData(0xe90d, fontFamily: _kFontFam);
  static const IconData guild_dimir = const IconData(0xe90e, fontFamily: _kFontFam);
  static const IconData guild_golgari = const IconData(0xe90f, fontFamily: _kFontFam);
  static const IconData guild_gruul = const IconData(0xe910, fontFamily: _kFontFam);
  static const IconData guild_izzet = const IconData(0xe911, fontFamily: _kFontFam);
  static const IconData guild_orzhov = const IconData(0xe912, fontFamily: _kFontFam);
  static const IconData guild_rakdos = const IconData(0xe913, fontFamily: _kFontFam);
  static const IconData guild_selesnya = const IconData(0xe914, fontFamily: _kFontFam);
  static const IconData guild_simic = const IconData(0xe915, fontFamily: _kFontFam);
  static const IconData clan_abzan = const IconData(0xe916, fontFamily: _kFontFam);
  static const IconData clan_jeskai = const IconData(0xe917, fontFamily: _kFontFam);
  static const IconData clan_mardu = const IconData(0xe918, fontFamily: _kFontFam);
  static const IconData clan_sultai = const IconData(0xe919, fontFamily: _kFontFam);
  static const IconData clan_temur = const IconData(0xe91a, fontFamily: _kFontFam);
  static const IconData clan_atarka = const IconData(0xe91b, fontFamily: _kFontFam);
  static const IconData clan_dromoka = const IconData(0xe91c, fontFamily: _kFontFam);
  static const IconData clan_kolaghan = const IconData(0xe91d, fontFamily: _kFontFam);
  static const IconData clan_ojutai = const IconData(0xe91e, fontFamily: _kFontFam);
  static const IconData clan_silumgar = const IconData(0xe91f, fontFamily: _kFontFam);
  static const IconData dfc_enchantment = const IconData(0xe920, fontFamily: _kFontFam);
  static const IconData power = const IconData(0xe921, fontFamily: _kFontFam);
  static const IconData toughness = const IconData(0xe922, fontFamily: _kFontFam);
  static const IconData artist_brush = const IconData(0xe923, fontFamily: _kFontFam);
  static const IconData artist_nib = const IconData(0xe924, fontFamily: _kFontFam);
  static const IconData multiple = const IconData(0xe925, fontFamily: _kFontFam);
  static const IconData polis_setessa = const IconData(0xe926, fontFamily: _kFontFam);
  static const IconData polis_akros = const IconData(0xe927, fontFamily: _kFontFam);
  static const IconData polis_meletis = const IconData(0xe928, fontFamily: _kFontFam);
}
