/// Flutter icons Mana
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Mana
///      fonts:
///       - asset: fonts/Mana.ttf
///
///
///
// ignore_for_file: constant_identifier_names

library;

import 'package:flutter/widgets.dart';

class ManaIcons {
  ManaIcons._();

  static const _kFontFam = 'Mana';
  static const String? _kFontPkg = null;

  static const IconData w = IconData(
    0xe800,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData u = IconData(
    0xe801,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData b = IconData(
    0xe802,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData r = IconData(
    0xe803,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData g = IconData(
    0xe804,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i0 = IconData(
    0xe805,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i1 = IconData(
    0xe806,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i2 = IconData(
    0xe807,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i3 = IconData(
    0xe808,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i4 = IconData(
    0xe809,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i5 = IconData(
    0xe80a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i6 = IconData(
    0xe80b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i7 = IconData(
    0xe80c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i8 = IconData(
    0xe80d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i9 = IconData(
    0xe80e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i10 = IconData(
    0xe80f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i11 = IconData(
    0xe810,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i12 = IconData(
    0xe811,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i13 = IconData(
    0xe812,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i14 = IconData(
    0xe813,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i15 = IconData(
    0xe814,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData x = IconData(
    0xe815,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData y = IconData(
    0xe816,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData z = IconData(
    0xe817,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData p__h = IconData(
    0xe818,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData s = IconData(
    0xe819,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tap = IconData(
    0xe81a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData untap = IconData(
    0xe81b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tap_alt = IconData(
    0xe81c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData chaos = IconData(
    0xe81d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData artifact = IconData(
    0xe81e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData creature = IconData(
    0xe81f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData enchantment = IconData(
    0xe820,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData instant = IconData(
    0xe821,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData land = IconData(
    0xe822,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData planeswalker = IconData(
    0xe823,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sorcery = IconData(
    0xe824,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData loyalty_down = IconData(
    0xe825,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData loyalty_zero = IconData(
    0xe826,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData loyalty_up = IconData(
    0xe827,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData loyalty_start = IconData(
    0xe828,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData flashback = IconData(
    0xe829,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i16 = IconData(
    0xe82a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i17 = IconData(
    0xe82b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i18 = IconData(
    0xe82c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i19 = IconData(
    0xe82d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i20 = IconData(
    0xe82e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData z_1 = IconData(
    0xe82f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData y_1 = IconData(
    0xe830,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData x_1 = IconData(
    0xe831,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData w_1 = IconData(
    0xe832,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData u_1 = IconData(
    0xe833,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData untap_1 = IconData(
    0xe834,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tap_1 = IconData(
    0xe835,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tap_alt_1 = IconData(
    0xe836,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tap_alt_2 = IconData(
    0xe837,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData s_1 = IconData(
    0xe838,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData r_1 = IconData(
    0xe839,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData p__h_1 = IconData(
    0xe83a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData paw_1 = IconData(
    0xe83b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData paw_2 = IconData(
    0xe83c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData infinity_1 = IconData(
    0xe83d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData g_1 = IconData(
    0xe83e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData e__energy_1 = IconData(
    0xe83f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData c_1 = IconData(
    0xe840,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData chaos_1 = IconData(
    0xe841,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData b_1 = IconData(
    0xe842,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData z_2 = IconData(
    0xe843,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData y_2 = IconData(
    0xe844,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData x_2 = IconData(
    0xe845,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData w_2 = IconData(
    0xe846,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData u_2 = IconData(
    0xe847,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData s_2 = IconData(
    0xe848,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData r_2 = IconData(
    0xe849,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData p__h_2 = IconData(
    0xe84a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData g_2 = IconData(
    0xe84b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData e__energy_2 = IconData(
    0xe84c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData c_2 = IconData(
    0xe84d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData b_2 = IconData(
    0xe84e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i9_1 = IconData(
    0xe84f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i8_1 = IconData(
    0xe850,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i7_1 = IconData(
    0xe851,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i6_1 = IconData(
    0xe852,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i5_1 = IconData(
    0xe853,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i4_1 = IconData(
    0xe854,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i3_1 = IconData(
    0xe855,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i2_1 = IconData(
    0xe856,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i20_1 = IconData(
    0xe857,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i18_1 = IconData(
    0xe858,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i1_1 = IconData(
    0xe859,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i19_1 = IconData(
    0xe85a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i16_1 = IconData(
    0xe85b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i17_1 = IconData(
    0xe85c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i15_1 = IconData(
    0xe85d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i14_1 = IconData(
    0xe85e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i12_1 = IconData(
    0xe85f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i13_1 = IconData(
    0xe860,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i11_1 = IconData(
    0xe861,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i10_1 = IconData(
    0xe862,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i100_1 = IconData(
    0xe863,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i1000000_1 = IconData(
    0xe864,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData half_1 = IconData(
    0xe865,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i0_1 = IconData(
    0xe866,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i100 = IconData(
    0xe900,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData i1000000 = IconData(
    0xe901,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData half = IconData(
    0xe902,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData infinity = IconData(
    0xe903,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData c = IconData(
    0xe904,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dfc_night = IconData(
    0xe905,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dfc_day = IconData(
    0xe906,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData energy = IconData(
    0xe907,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dfc_ignite = IconData(
    0xe908,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dfc_spark = IconData(
    0xe909,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dfc_emrakul = IconData(
    0xe90a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dfc_moon = IconData(
    0xe90b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData guild_azorius = IconData(
    0xe90c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData guild_boros = IconData(
    0xe90d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData guild_dimir = IconData(
    0xe90e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData guild_golgari = IconData(
    0xe90f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData guild_gruul = IconData(
    0xe910,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData guild_izzet = IconData(
    0xe911,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData guild_orzhov = IconData(
    0xe912,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData guild_rakdos = IconData(
    0xe913,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData guild_selesnya = IconData(
    0xe914,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData guild_simic = IconData(
    0xe915,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData clan_abzan = IconData(
    0xe916,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData clan_jeskai = IconData(
    0xe917,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData clan_mardu = IconData(
    0xe918,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData clan_sultai = IconData(
    0xe919,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData clan_temur = IconData(
    0xe91a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData clan_atarka = IconData(
    0xe91b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData clan_dromoka = IconData(
    0xe91c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData clan_kolaghan = IconData(
    0xe91d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData clan_ojutai = IconData(
    0xe91e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData clan_silumgar = IconData(
    0xe91f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dfc_enchantment = IconData(
    0xe920,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData power = IconData(
    0xe921,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData toughness = IconData(
    0xe922,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData artist_brush = IconData(
    0xe923,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData artist_nib = IconData(
    0xe924,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData multiple__tribal = IconData(
    0xe925,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData polis_setessa = IconData(
    0xe926,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData polis_akros = IconData(
    0xe927,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData polis_meletis = IconData(
    0xe928,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData acorn = IconData(
    0xe929,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData saga = IconData(
    0xe92a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_arrow = IconData(
    0xe92b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_brick = IconData(
    0xe92c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_charge = IconData(
    0xe92d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_devotion = IconData(
    0xe92e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_doom = IconData(
    0xe92f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_echo = IconData(
    0xe930,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_flame = IconData(
    0xe931,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_flood = IconData(
    0xe932,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_fungus = IconData(
    0xe933,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_gold = IconData(
    0xe934,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_ki = IconData(
    0xe935,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_lore = IconData(
    0xe936,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_loyalty = IconData(
    0xe937,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_mining = IconData(
    0xe938,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_minus = IconData(
    0xe939,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_muster = IconData(
    0xe93a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_paw = IconData(
    0xe93b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_pin = IconData(
    0xe93c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_plus = IconData(
    0xe93d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_scream = IconData(
    0xe93e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_skeleton = IconData(
    0xe93f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_skull = IconData(
    0xe940,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_slime = IconData(
    0xe941,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_time = IconData(
    0xe942,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_minus_uneven = IconData(
    0xe943,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_plus_uneven = IconData(
    0xe944,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_verse = IconData(
    0xe945,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_vortex = IconData(
    0xe946,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_activated = IconData(
    0xe947,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_adventure = IconData(
    0xe948,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_convoke_original = IconData(
    0xe949,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_ascend = IconData(
    0xe94a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_deathtouch = IconData(
    0xe94b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_defender = IconData(
    0xe94c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_doublestrike = IconData(
    0xe94d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_enrage_original = IconData(
    0xe94e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_explore = IconData(
    0xe94f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_firststrike = IconData(
    0xe950,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_flash = IconData(
    0xe951,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_flying = IconData(
    0xe952,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_haste = IconData(
    0xe953,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_hexproof = IconData(
    0xe954,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_hexproof_black = IconData(
    0xe955,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_hexproof_blue = IconData(
    0xe956,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_hexproof_green = IconData(
    0xe957,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_hexproof_red = IconData(
    0xe958,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_hexproof_white = IconData(
    0xe959,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_indestructible = IconData(
    0xe95a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_jumpstart = IconData(
    0xe95b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_lifelink = IconData(
    0xe95c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_menace = IconData(
    0xe95d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_mentor = IconData(
    0xe95e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_raid = IconData(
    0xe95f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_reach = IconData(
    0xe960,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_revolt = IconData(
    0xe961,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_static = IconData(
    0xe962,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_surveil = IconData(
    0xe963,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_trample = IconData(
    0xe964,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_transform = IconData(
    0xe965,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_triggered = IconData(
    0xe966,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_undergrowth = IconData(
    0xe967,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_vigilance = IconData(
    0xe968,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_escape = IconData(
    0xe969,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_summoning_sickness = IconData(
    0xe96a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_spectacle = IconData(
    0xe96b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rarity = IconData(
    0xe96c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData token = IconData(
    0xe96d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData phenomenon = IconData(
    0xe96e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData plane = IconData(
    0xe96f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData scheme = IconData(
    0xe970,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData vanguard = IconData(
    0xe971,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData conspiracy = IconData(
    0xe972,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_riot = IconData(
    0xe973,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_adamant = IconData(
    0xe974,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_adapt = IconData(
    0xe975,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_addendum = IconData(
    0xe976,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_afflict = IconData(
    0xe977,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_afterlife = IconData(
    0xe978,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_aftermath = IconData(
    0xe979,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_amass__ability_amass_zombies = IconData(
    0xe97a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_companion = IconData(
    0xe97b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_constellation = IconData(
    0xe97c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_devotion = IconData(
    0xe97d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_embalm = IconData(
    0xe97e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_eternalize = IconData(
    0xe97f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_mutate = IconData(
    0xe980,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_proliferate = IconData(
    0xe981,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_prowess = IconData(
    0xe982,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dfc_modal_face = IconData(
    0xe983,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dfc_modal_back = IconData(
    0xe984,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData multicolor = IconData(
    0xe985,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData multicolor_border = IconData(
    0xe986,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_party = IconData(
    0xe987,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_landfall = IconData(
    0xe988,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_kicker = IconData(
    0xe989,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ci_1 = IconData(
    0xe98a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ci_2 = IconData(
    0xe98b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ci_3 = IconData(
    0xe98c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ci_4 = IconData(
    0xe98d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ci_5 = IconData(
    0xe98e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dfc_lesson = IconData(
    0xe98f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_foretell = IconData(
    0xe990,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_boast = IconData(
    0xe991,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_ward = IconData(
    0xe992,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_magecraft = IconData(
    0xe993,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_learn = IconData(
    0xe994,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_dungeon = IconData(
    0xe995,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData s_mtga = IconData(
    0xe996,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData w_original = IconData(
    0xe997,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData w_list = IconData(
    0xe998,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_d20 = IconData(
    0xe999,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData school_lorehold = IconData(
    0xe99a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData school_lorehold_inner = IconData(
    0xe99b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData school_prismari = IconData(
    0xe99c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData school_prismari_inner = IconData(
    0xe99d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData school_quandrix = IconData(
    0xe99e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData school_quandrix_inner = IconData(
    0xe99f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData school_silverquill = IconData(
    0xe9a0,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData school_silverquill_inner = IconData(
    0xe9a1,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData school_witherbloom = IconData(
    0xe9a2,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData school_witherbloom_outer = IconData(
    0xe9a3,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData school_witherbloom_inner = IconData(
    0xe9a4,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_fabricate = IconData(
    0xe9a5,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_changeling = IconData(
    0xe9a6,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_domain = IconData(
    0xe9a7,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_day_night = IconData(
    0xe9a8,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_daybound_nightbound = IconData(
    0xe9a9,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_coven = IconData(
    0xe9aa,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_investigate = IconData(
    0xe9ab,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_decayed = IconData(
    0xe9ac,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_cleave = IconData(
    0xe9ad,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_disturb = IconData(
    0xe9ae,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_exploit = IconData(
    0xe9af,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_training = IconData(
    0xe9b0,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_channel = IconData(
    0xe9b1,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_ninjutsu = IconData(
    0xe9b2,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_reconfigure = IconData(
    0xe9b3,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_blitz = IconData(
    0xe9b4,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_alliance = IconData(
    0xe9b5,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_obscura = IconData(
    0xe9b6,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_casualty = IconData(
    0xe9b7,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_hideaway = IconData(
    0xe9b8,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_read_ahead = IconData(
    0xe9b9,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_enlist = IconData(
    0xe9ba,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_specialize = IconData(
    0xe9bb,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_unearth = IconData(
    0xe9bc,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_meld = IconData(
    0xe9bd,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_prototype = IconData(
    0xe9be,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_toxic = IconData(
    0xe9bf,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_corrupted = IconData(
    0xe9c0,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_for_mirrodin = IconData(
    0xe9c1,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_stun = IconData(
    0xe9c2,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_shield = IconData(
    0xe9c3,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ticket__tk = IconData(
    0xe9c4,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dfc_land = IconData(
    0xe9c5,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData commander = IconData(
    0xe9c6,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData level_main = IconData(
    0xe9c7,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData level_alt = IconData(
    0xe9c8,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_goad = IconData(
    0xe9c9,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData hand = IconData(
    0xe9ca,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData library_icon = IconData(
    0xe9cb,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData graveyard = IconData(
    0xe9cc,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData exile = IconData(
    0xe9cd,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_combat_condition = IconData(
    0xe9ce,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dfc_saga = IconData(
    0xe9cf,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dfc_saga_creature = IconData(
    0xe9d0,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData battle = IconData(
    0xe9d1,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData battle_siege = IconData(
    0xe9d2,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dfc_front = IconData(
    0xe9d3,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dfc_back = IconData(
    0xe9d4,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dfc_meld = IconData(
    0xe9d5,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dfc_facedown = IconData(
    0xe9d6,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData defense = IconData(
    0xe9d7,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData defense_border = IconData(
    0xe9d8,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_backup = IconData(
    0xe9d9,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_convoke = IconData(
    0xe9da,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_incubate = IconData(
    0xe9db,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_enrage = IconData(
    0xe9dc,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_damage = IconData(
    0xe9dd,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_improvise = IconData(
    0xe9de,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_ring_bearer = IconData(
    0xe9df,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_amass_orcs = IconData(
    0xe9e0,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_the_ring_tempts_you = IconData(
    0xe9e1,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_bargain = IconData(
    0xe9e2,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_celebration = IconData(
    0xe9e3,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_haktos_the_unscarred = IconData(
    0xe9e4,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_robber_of_the_rich = IconData(
    0xe9e5,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData role_cursed = IconData(
    0xe9e6,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData role_monster = IconData(
    0xe9e7,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData role_royal = IconData(
    0xe9e8,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData role_sorceror = IconData(
    0xe9e9,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData role_wicked = IconData(
    0xe9ea,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData role_young_hero = IconData(
    0xe9eb,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_void = IconData(
    0xe9ec,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_mtg = IconData(
    0xe9ed,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_mtg10 = IconData(
    0xe9ee,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_mtg15 = IconData(
    0xe9ef,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_colorpie = IconData(
    0xe9f0,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_desparked = IconData(
    0xe9f1,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_flavor_aestheticconsultation = IconData(
    0xe9f2,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_flavor_farewelltoarms = IconData(
    0xe9f3,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_flavor_monkeymonkeymonkey = IconData(
    0xe9f4,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_flavor_moxlotus = IconData(
    0xe9f5,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_flavor_myfirsttome = IconData(
    0xe9f6,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_flavor_shoetree = IconData(
    0xe9f7,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_flavor_whenfluffybunniesattack = IconData(
    0xe9f8,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_herospath_1 = IconData(
    0xe9f9,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_herospath_2 = IconData(
    0xe9fa,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_herospath_3 = IconData(
    0xe9fb,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_herospath_4 = IconData(
    0xe9fc,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_herospath_5 = IconData(
    0xe9fd,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_herospath_6 = IconData(
    0xe9fe,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_herospath_7 = IconData(
    0xe9ff,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_herospath_8 = IconData(
    0xea00,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_herospath_9 = IconData(
    0xea01,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_herospath = IconData(
    0xea02,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_mirran = IconData(
    0xea03,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_cutiemark_gems = IconData(
    0xea04,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_cutiemark_sparkle = IconData(
    0xea05,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_cutiemark_waningmoon = IconData(
    0xea06,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_cutiemark_waxingmoon = IconData(
    0xea07,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_agentsofsneak = IconData(
    0xea08,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_crossbreedlabs = IconData(
    0xea09,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_goblinexplosioneers = IconData(
    0xea0a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_leagueofdastardlydoom = IconData(
    0xea0b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_orderofthewidget = IconData(
    0xea0c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_brokers = IconData(
    0xea0d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_cabaretti = IconData(
    0xea0e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_maestros = IconData(
    0xea0f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_obscura = IconData(
    0xea10,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_riveteers = IconData(
    0xea11,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_conspiracy = IconData(
    0xea12,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_judgeacademy = IconData(
    0xea13,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_dengekimaoh = IconData(
    0xea14,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_corocoro = IconData(
    0xea15,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_fnm = IconData(
    0xea16,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_dnd = IconData(
    0xea17,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_transformers = IconData(
    0xea18,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_nerf = IconData(
    0xea19,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_mps = IconData(
    0xea1a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_wotc = IconData(
    0xea1b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_wpn = IconData(
    0xea1c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_dci = IconData(
    0xea1d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_arena = IconData(
    0xea1e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_grandprix = IconData(
    0xea1f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_grandprix2 = IconData(
    0xea20,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_juniorapac = IconData(
    0xea21,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_junioreurope = IconData(
    0xea22,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_junior = IconData(
    0xea23,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_japanjunior = IconData(
    0xea24,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_scholarship = IconData(
    0xea25,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_protour = IconData(
    0xea26,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_cutiemark_apples = IconData(
    0xea27,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_cutiemark_balloons = IconData(
    0xea28,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_cutiemark_butterflies = IconData(
    0xea29,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_cutiemark_rainbow = IconData(
    0xea2a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_trumpkatsumai = IconData(
    0xea2b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData watermark_flavor_manascrew = IconData(
    0xea2c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData l = IconData(
    0xea2d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData d = IconData(
    0xea2e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData power_arena = IconData(
    0xea2f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData toughness_arena = IconData(
    0xea30,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData tap_4ed = IconData(
    0xea31,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData paw = IconData(
    0xea32,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_exalted = IconData(
    0xea33,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_disguise = IconData(
    0xea34,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_cloak = IconData(
    0xea35,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_collect_evidence = IconData(
    0xea36,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_suspect = IconData(
    0xea37,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_surveil_2 = IconData(
    0xea38,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_case_solved = IconData(
    0xea39,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_case_solved_print = IconData(
    0xea3a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_delve = IconData(
    0xea3b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_ferocious = IconData(
    0xea3c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_outlast = IconData(
    0xea3d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_morph = IconData(
    0xea3e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_craft = IconData(
    0xea3f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_discover = IconData(
    0xea40,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_descend = IconData(
    0xea41,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_plot = IconData(
    0xea42,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_saddle = IconData(
    0xea43,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_spree = IconData(
    0xea44,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_crime = IconData(
    0xea45,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_gift = IconData(
    0xea46,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_offspring = IconData(
    0xea47,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_valiant = IconData(
    0xea48,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_forage = IconData(
    0xea49,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_expend = IconData(
    0xea4a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_lifelink_2 = IconData(
    0xea4b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_impending = IconData(
    0xea4c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_eerie = IconData(
    0xea4d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_survival = IconData(
    0xea4e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_manifest_dread = IconData(
    0xea4f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_rad = IconData(
    0xea50,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_deathtouch = IconData(
    0xea51,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_brick_print = IconData(
    0xea52,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_charge_print = IconData(
    0xea53,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData counter_finality = IconData(
    0xea54,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData spree = IconData(
    0xea55,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData party_wizard = IconData(
    0xea56,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData party_warrior = IconData(
    0xea57,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData party_rogue = IconData(
    0xea58,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData party_cleric = IconData(
    0xea59,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_annihilator = IconData(
    0xea5a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_battle_cry = IconData(
    0xea5b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_unblockable = IconData(
    0xea5c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_cannot_block = IconData(
    0xea5d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_cannot_untap = IconData(
    0xea5e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_cohort = IconData(
    0xea5f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_copy = IconData(
    0xea60,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_deathtouch = IconData(
    0xea61,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_defender = IconData(
    0xea62,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_delirium = IconData(
    0xea63,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_detain = IconData(
    0xea64,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_double_strike = IconData(
    0xea65,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_dfc = IconData(
    0xea66,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_evolve = IconData(
    0xea67,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_exalter = IconData(
    0xea68,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_exile = IconData(
    0xea69,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_fading = IconData(
    0xea6a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_fear = IconData(
    0xea6b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_first_strike = IconData(
    0xea6c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_flying = IconData(
    0xea6d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_forestwalk = IconData(
    0xea6e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_haste = IconData(
    0xea6f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_haunt = IconData(
    0xea70,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_hexproof = IconData(
    0xea71,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_indestructible = IconData(
    0xea72,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_infect = IconData(
    0xea73,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_ingest = IconData(
    0xea74,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_intimidate = IconData(
    0xea75,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_islandwalk = IconData(
    0xea76,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_legendary = IconData(
    0xea77,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_lifelink = IconData(
    0xea78,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_menace = IconData(
    0xea79,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_monstrous = IconData(
    0xea7a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_mountainwalk = IconData(
    0xea7b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_must_attack = IconData(
    0xea7c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_plainswalk = IconData(
    0xea7d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_prevent_damage = IconData(
    0xea7e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_protection_black = IconData(
    0xea7f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_protection_blue = IconData(
    0xea80,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_protection_green = IconData(
    0xea81,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_protection_red = IconData(
    0xea82,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_protection_white = IconData(
    0xea83,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_protection = IconData(
    0xea84,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_rally = IconData(
    0xea85,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_regenerate = IconData(
    0xea86,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_renowned = IconData(
    0xea87,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_shroud = IconData(
    0xea88,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_skulk = IconData(
    0xea89,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_soulshift = IconData(
    0xea8a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_swampwalk = IconData(
    0xea8b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_temporary_control = IconData(
    0xea8c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_totem_armor = IconData(
    0xea8d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_trample = IconData(
    0xea8e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_undying = IconData(
    0xea8f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_vigilance = IconData(
    0xea90,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ability_duels_vigilance_1 = IconData(
    0xea91,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
}
