name: counter_spell_new
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# RICORDA DI CAMBIARE QUESTO NUMERO IN SETTINGSBLOC STATIC VERSIONCODE
version: 3.2.5+87
# RICORDA DI CAMBIARE QUESTO NUMERO IN SETTINGSBLOC STATIC VERSIONCODE
# PER IL CHANGELOG

environment:
  sdk: ">=2.7.0 <3.0.0"

publish_to: none

dependencies:
  sid_ui:
    path: ../sid_ui
  sid_utils:
    path: ../sid_utils
  sid_bloc:
    path: ../sid_bloc
  stage:
    path: ../stage_2
  animations: ^1.1.1
  auto_size_text: ^2.1.0
  badges: ^1.1.4
  cached_network_image: ^2.0.0-rc
  division: ^0.7.0
  equatable: ^1.0.0
  ext_storage: ^1.0.3
  fl_chart: ^0.8.1
  flutter_reorderable_list: ^0.1.5
  flutter_vector_icons: ^0.2.1
  http: ^0.12.0+2
  in_app_purchase: ^0.2.2+4
  permission_handler: ^5.0.1+1
  rxdart: ^0.22.6
  screen: ^0.0.4
  sleek_circular_slider: ^1.1.0
  smooth_page_indicator: ^0.1.4
  time: ^1.2.0
  url_launcher: ^5.2.5
  vibrate: ^0.0.4
  # flutter_statusbarcolor: ^0.2.0
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  image_path: "assets/images/android_legacy.png"
  image_path_android: "assets/images/android_legacy.png"
  image_path_ios: "assets/images/white_on_black.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/white_on_black.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/fully_transparent.png" # only available for Android 8.0 devices and above

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/command_bros/logo.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family:  CounterSpell
      fonts:
       - asset: assets/fonts/CounterSpell.ttf
    - family:  Dices
      fonts:
       - asset: assets/fonts/Dices.ttf
    - family:  MagicIcons
      fonts:
       - asset: assets/fonts/MagicIcons.ttf
    - family:  ShieldIcons
      fonts:
       - asset: assets/fonts/ShieldIcons.ttf
    - family:  ManaIcons
      fonts:
       - asset: assets/fonts/ManaIcons.ttf
    - family:  Keyrune
      fonts:
      - asset: assets/fonts/keyrune.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
