

const Map<String,String> set_names = {    
  "eld": "Throne of Eldraine",
  "c19": "Commander 2019",
  "tc19": "Commander 2019 Tokens",
  "ps19": "San Diego Comic-Con 2019",
  "pm20": "Core Set 2020 Promos",
  "tm20": "Core Set 2020 Tokens",
  "ppp1": "M20 Promo Packs",
  "m20": "Core Set 2020",
  "ss2": "Signature Spellbook: Gideon",
  "pmh1": "Modern Horizons Promos",
  "mh1": "Modern Horizons",
  "tmh1": "Modern Horizons Tokens",
  "pwar": "War of the Spark Promos",
  "twar": "War of the Spark Tokens",
  "war": "War of the Spark",
  "j19": "Judge Gift Cards 2019",
  "prw2": "RNA Ravnica Weekend",
  "gk2": "RNA Guild Kit",
  "tgk2": "RNA Guild Kit Tokens",
  "prna": "Ravnica Allegiance Promos",
  "rna": "Ravnica Allegiance",
  "trna": "Ravnica Allegiance Tokens",
  "pf19": "MagicFest 2019",
  "opca": "Planechase Anthology Planes",
  "puma": "Ultimate Box Topper",
  "uma": "Ultimate Masters",
  "tuma": "Ultimate Masters Tokens",
  "gnt": "Game Night",
  "g18": "M19 Gift Pack",
  "gk1": "GRN Guild Kit",
  "tgk1": "GRN Guild Kit Tokens",
  "tgrn": "Guilds of Ravnica Tokens",
  "pgrn": "Guilds of Ravnica Promos",
  "grn": "Guilds of Ravnica",
  "prwk": "GRN Ravnica Weekend",
  "med": "Mythic Edition",
  "tmed": "Mythic Edition Tokens",
  "oc18": "Commander 2018 Oversized",
  "tc18": "Commander 2018 Tokens",
  "c18": "Commander 2018",
  "htr17": "2017 Heroes of the Realm",
  "ps18": "San Diego Comic-Con 2018",
  "ana": "Arena New Player Experience",
  "pana": "MTG Arena Promos",
  "pm19": "Core Set 2019 Promos",
  "tm19": "Core Set 2019 Tokens",
  "pss3": "M19 Standard Showdown",
  "m19": "Core Set 2019",
  "gs1": "Global Series Jiang Yanggu & Mu Yanling",
  "ss1": "Signature Spellbook: Jace",
  "pbbd": "Battlebond Promos",
  "cm2": "Commander Anthology Volume II",
  "tcm2": "Commander Anthology Volume II Tokens",
  "tbbd": "Battlebond Tokens",
  "bbd": "Battlebond",
  "pdom": "Dominaria Promos",
  "dom": "Dominaria",
  "tdom": "Dominaria Tokens",
  "ddu": "Duel Decks: Elves vs. Inventors",
  "tddu": "Duel Decks: Elves vs. Inventors Tokens",
  "a25": "Masters 25",
  "ta25": "Masters 25 Tokens",
  "plny": "2018 Lunar New Year",
  "pnat": "Nationals Promos",
  "prix": "Rivals of Ixalan Promos",
  "trix": "Rivals of Ixalan Tokens",
  "rix": "Rivals of Ixalan",
  "j18": "Judge Gift Cards 2018",
  "f18": "Friday Night Magic 2018",
  "ust": "Unstable",
  "tima": "Iconic Masters Tokens",
  "v17": "From the Vault: Transform",
  "pxtc": "XLN Treasure Chest",
  "e02": "Explorers of Ixalan",
  "ima": "Iconic Masters",
  "tust": "Unstable Tokens",
  "pust": "Unstable Promos",
  "ddt": "Duel Decks: Merfolk vs. Goblins",
  "tddt": "Duel Decks: Merfolk vs. Goblins Tokens",
  "g17": "2017 Gift Pack",
  "pxln": "Ixalan Promos",
  "xln": "Ixalan",
  "txln": "Ixalan Tokens",
  "pss2": "XLN Standard Showdown",
  "h17": "HasCon 2017",
  "htr": "2016 Heroes of the Realm",
  "te01": "Archenemy: Nicol Bolas Tokens",
  "oc17": "Commander 2017 Oversized",
  "c17": "Commander 2017",
  "tc17": "Commander 2017 Tokens",
  "ps17": "San Diego Comic-Con 2017",
  "phou": "Hour of Devastation Promos",
  "hou": "Hour of Devastation",
  "thou": "Hour of Devastation Tokens",
  "oe01": "Archenemy: Nicol Bolas Schemes",
  "e01": "Archenemy: Nicol Bolas",
  "tcma": "Commander Anthology Tokens",
  "cma": "Commander Anthology",
  "pakh": "Amonkhet Promos",
  "akh": "Amonkhet",
  "takh": "Amonkhet Tokens",
  "mp2": "Amonkhet Invocations",
  "w17": "Welcome Deck 2017",
  "dds": "Duel Decks: Mind vs. Might",
  "tdds": "Duel Decks: Mind vs. Might Tokens",
  "tmm3": "Modern Masters 2017 Tokens",
  "mm3": "Modern Masters 2017",
  "paer": "Aether Revolt Promos",
  "taer": "Aether Revolt Tokens",
  "aer": "Aether Revolt",
  "l17": "League Tokens 2017",
  "j17": "Judge Gift Cards 2017",
  "f17": "Friday Night Magic 2017",
  "tpca": "Planechase Anthology Tokens",
  "pca": "Planechase Anthology",
  "pz2": "Treasure Chest",
  "oc16": "Commander 2016 Oversized",
  "c16": "Commander 2016",
  "tc16": "Commander 2016 Tokens",
  "ps16": "San Diego Comic-Con 2016",
  "pkld": "Kaladesh Promos",
  "kld": "Kaladesh",
  "tkld": "Kaladesh Tokens",
  "mps": "Kaladesh Inventions",
  "ddr": "Duel Decks: Nissa vs. Ob Nixilis",
  "cn2": "Conspiracy: Take the Crown",
  "tcn2": "Conspiracy: Take the Crown Tokens",
  "v16": "From the Vault: Lore",
  "pemn": "Eldritch Moon Promos",
  "emn": "Eldritch Moon",
  "temn": "Eldritch Moon Tokens",
  "tema": "Eternal Masters Tokens",
  "ema": "Eternal Masters",
  "psoi": "Shadows over Innistrad Promos",
  "soi": "Shadows over Innistrad",
  "tsoi": "Shadows over Innistrad Tokens",
  "w16": "Welcome Deck 2016",
  "ddq": "Duel Decks: Blessed vs. Cursed",
  "pogw": "Oath of the Gatewatch Promos",
  "togw": "Oath of the Gatewatch Tokens",
  "ogw": "Oath of the Gatewatch",
  "l16": "League Tokens 2016",
  "j16": "Judge Gift Cards 2016",
  "f16": "Friday Night Magic 2016",
  "pz1": "Legendary Cube Prize Pack",
  "oc15": "Commander 2015 Oversized",
  "c15": "Commander 2015",
  "tc15": "Commander 2015 Tokens",
  "pbfz": "Battle for Zendikar Promos",
  "bfz": "Battle for Zendikar",
  "tbfz": "Battle for Zendikar Tokens",
  "pss1": "BFZ Standard Series",
  "exp": "Zendikar Expeditions",
  "ddp": "Duel Decks: Zendikar vs. Eldrazi",
  "v15": "From the Vault: Angels",
  "cp3": "Magic Origins Clash Pack",
  "pori": "Magic Origins Promos",
  "tori": "Magic Origins Tokens",
  "ori": "Magic Origins",
  "ps15": "San Diego Comic-Con 2015",
  "mm2": "Modern Masters 2015",
  "tmm2": "Modern Masters 2015 Tokens",
  "tpr": "Tempest Remastered",
  "ptkdf": "Tarkir Dragonfury",
  "pdtk": "Dragons of Tarkir Promos",
  "tdtk": "Dragons of Tarkir Tokens",
  "dtk": "Dragons of Tarkir",
  "ddo": "Duel Decks: Elspeth vs. Kiora",
  "pfrf": "Fate Reforged Promos",
  "cp2": "Fate Reforged Clash Pack",
  "tfrf": "Fate Reforged Tokens",
  "frf": "Fate Reforged",
  "ugin": "Ugin's Fate",
  "l15": "League Tokens 2015",
  "f15": "Friday Night Magic 2015",
  "j15": "Judge Gift Cards 2015",
  "tjvc": "Duel Decks Anthology: Jace vs. Chandra Tokens",
  "tdvd": "Duel Decks Anthology: Divine vs. Demonic Tokens",
  "tgvl": "Duel Decks Anthology: Garruk vs. Liliana Tokens",
  "dvd": "Duel Decks Anthology: Divine vs. Demonic",
  "tevg": "Duel Decks Anthology: Elves vs. Goblins Tokens",
  "gvl": "Duel Decks Anthology: Garruk vs. Liliana",
  "evg": "Duel Decks Anthology: Elves vs. Goblins",
  "jvc": "Duel Decks Anthology: Jace vs. Chandra",
  "oc14": "Commander 2014 Oversized",
  "tc14": "Commander 2014 Tokens",
  "c14": "Commander 2014",
  "pktk": "Khans of Tarkir Promos",
  "tktk": "Khans of Tarkir Tokens",
  "ktk": "Khans of Tarkir",
  "ddn": "Duel Decks: Speed vs. Cunning",
  "v14": "From the Vault: Annihilation",
  "m15": "Magic 2015",
  "cp1": "Magic 2015 Clash Pack",
  "tm15": "Magic 2015 Tokens",
  "pm15": "Magic 2015 Promos",
  "ppc1": "M15 Prerelease Challenge",
  "ps14": "San Diego Comic-Con 2014",
  "vma": "Vintage Masters",
  "tcns": "Conspiracy Tokens",
  "cns": "Conspiracy",
  "tmd1": "Modern Event Deck 2014 Tokens",
  "md1": "Modern Event Deck 2014",
  "tdag": "Defeat a God",
  "thp3": "Journey into Nyx Hero's Path",
  "jou": "Journey into Nyx",
  "tjou": "Journey into Nyx Tokens",
  "pjou": "Journey into Nyx Promos",
  "tddm": "Duel Decks: Jace vs. Vraska Tokens",
  "ddm": "Duel Decks: Jace vs. Vraska",
  "tbth": "Battle the Horde",
  "thp2": "Born of the Gods Hero's Path",
  "tbng": "Born of the Gods Tokens",
  "bng": "Born of the Gods",
  "pbng": "Born of the Gods Promos",
  "pdp14": "Duels of the Planeswalkers Promos 2014",
  "pi14": "IDW Comics 2014",
  "l14": "League Tokens 2014",
  "j14": "Judge Gift Cards 2014",
  "f14": "Friday Night Magic 2014",
  "oc13": "Commander 2013 Oversized",
  "c13": "Commander 2013",
  "tfth": "Face the Hydra",
  "tths": "Theros Tokens",
  "ths": "Theros",
  "thp1": "Theros Hero's Path",
  "pths": "Theros Promos",
  "ddl": "Duel Decks: Heroes vs. Monsters",
  "tddl": "Duel Decks: Heroes vs. Monsters Tokens",
  "v13": "From the Vault: Twenty",
  "tm14": "Magic 2014 Tokens",
  "m14": "Magic 2014",
  "pm14": "Magic 2014 Promos",
  "psdc": "San Diego Comic-Con 2013",
  "mma": "Modern Masters",
  "tmma": "Modern Masters Tokens",
  "dgm": "Dragon's Maze",
  "tdgm": "Dragon's Maze Tokens",
  "pdgm": "Dragon's Maze Promos",
  "pwcq": "World Magic Cup Qualifiers",
  "ddk": "Duel Decks: Sorin vs. Tibalt",
  "tddk": "Duel Decks: Sorin vs. Tibalt Tokens",
  "gtc": "Gatecrash",
  "tgtc": "Gatecrash Tokens",
  "pgtc": "Gatecrash Promos",
  "pdp13": "Duels of the Planeswalkers Promos 2013",
  "pi13": "IDW Comics 2013",
  "l13": "League Tokens 2013",
  "j13": "Judge Gift Cards 2013",
  "f13": "Friday Night Magic 2013",
  "ocm1": "Commander's Arsenal Oversized",
  "cm1": "Commander's Arsenal",
  "rtr": "Return to Ravnica",
  "prtr": "Return to Ravnica Promos",
  "trtr": "Return to Ravnica Tokens",
  "tddj": "Duel Decks: Izzet vs. Golgari Tokens",
  "ddj": "Duel Decks: Izzet vs. Golgari",
  "v12": "From the Vault: Realms",
  "m13": "Magic 2013",
  "tm13": "Magic 2013 Tokens",
  "pm13": "Magic 2013 Promos",
  "opc2": "Planechase 2012 Planes",
  "pc2": "Planechase 2012",
  "tavr": "Avacyn Restored Tokens",
  "avr": "Avacyn Restored",
  "phel": "Open the Helvault",
  "pavr": "Avacyn Restored Promos",
  "ddi": "Duel Decks: Venser vs. Koth",
  "tddi": "Duel Decks: Venser vs. Koth Tokens",
  "tdka": "Dark Ascension Tokens",
  "dka": "Dark Ascension",
  "pdka": "Dark Ascension Promos",
  "pidw": "IDW Comics 2012",
  "pwp12": "Wizards Play Network 2012",
  "pdp12": "Duels of the Planeswalkers Promos 2012",
  "l12": "League Tokens 2012",
  "j12": "Judge Gift Cards 2012",
  "f12": "Friday Night Magic 2012",
  "pd3": "Premium Deck Series: Graveborn",
  "isd": "Innistrad",
  "tisd": "Innistrad Tokens",
  "pisd": "Innistrad Promos",
  "ddh": "Duel Decks: Ajani vs. Nicol Bolas",
  "tddh": "Duel Decks: Ajani vs. Nicol Bolas Tokens",
  "v11": "From the Vault: Legends",
  "tm12": "Magic 2012 Tokens",
  "m12": "Magic 2012",
  "pm12": "Magic 2012 Promos",
  "ocmd": "Commander 2011 Oversized",
  "pcmd": "Commander 2011 Launch Party",
  "cmd": "Commander 2011",
  "td2": "Duel Decks: Mirrodin Pure vs. New Phyrexia",
  "nph": "New Phyrexia",
  "tnph": "New Phyrexia Tokens",
  "pnph": "New Phyrexia Promos",
  "tddg": "Duel Decks: Knights vs. Dragons Tokens",
  "ddg": "Duel Decks: Knights vs. Dragons",
  "tmbs": "Mirrodin Besieged Tokens",
  "mbs": "Mirrodin Besieged",
  "pmbs": "Mirrodin Besieged Promos",
  "me4": "Masters Edition IV",
  "pmps11": "Magic Premiere Shop 2011",
  "pdp11": "Duels of the Planeswalkers Promos 2011",
  "pwp11": "Wizards Play Network 2011",
  "p11": "Magic Player Rewards 2011",
  "ps11": "Salvat 2011",
  "f11": "Friday Night Magic 2011",
  "olgc": "Legacy Championship",
  "g11": "Judge Gift Cards 2011",
  "pd2": "Premium Deck Series: Fire and Lightning",
  "td0": "Magic Online Theme Decks",
  "tsom": "Scars of Mirrodin Tokens",
  "som": "Scars of Mirrodin",
  "psom": "Scars of Mirrodin Promos",
  "ddf": "Duel Decks: Elspeth vs. Tezzeret",
  "tddf": "Duel Decks: Elspeth vs. Tezzeret Tokens",
  "v10": "From the Vault: Relics",
  "m11": "Magic 2011",
  "tm11": "Magic 2011 Tokens",
  "pm11": "Magic 2011 Promos",
  "oarc": "Archenemy Schemes",
  "arc": "Archenemy",
  "parc": "Promotional Schemes",
  "dpa": "Duels of the Planeswalkers",
  "proe": "Rise of the Eldrazi Promos",
  "roe": "Rise of the Eldrazi",
  "troe": "Rise of the Eldrazi Tokens",
  "dde": "Duel Decks: Phyrexia vs. the Coalition",
  "tdde": "Duel Decks: Phyrexia vs. the Coalition Tokens",
  "pwwk": "Worldwake Promos",
  "wwk": "Worldwake",
  "twwk": "Worldwake Tokens",
  "pdp10": "Duels of the Planeswalkers Promos 2010",
  "pwp10": "Wizards Play Network 2010",
  "pmps10": "Magic Premiere Shop 2010",
  "g10": "Judge Gift Cards 2010",
  "p10": "Magic Player Rewards 2010",
  "f10": "Friday Night Magic 2010",
  "h09": "Premium Deck Series: Slivers",
  "tddd": "Duel Decks: Garruk vs. Liliana Tokens",
  "ddd": "Duel Decks: Garruk vs. Liliana",
  "pzen": "Zendikar Promos",
  "tzen": "Zendikar Tokens",
  "zen": "Zendikar",
  "me3": "Masters Edition III",
  "ohop": "Planechase Planes",
  "hop": "Planechase",
  "phop": "Promotional Planes",
  "v09": "From the Vault: Exiled",
  "tm10": "Magic 2010 Tokens",
  "m10": "Magic 2010",
  "pm10": "Magic 2010 Promos",
  "arb": "Alara Reborn",
  "tarb": "Alara Reborn Tokens",
  "ddc": "Duel Decks: Divine vs. Demonic",
  "tddc": "Duel Decks: Divine vs. Demonic Tokens",
  "purl": "URL/Convention Promos",
  "tcon": "Conflux Tokens",
  "con": "Conflux",
  "pbok": "Miscellaneous Book Promos",
  "pwp09": "Wizards Play Network 2009",
  "pdtp": "Duels of the Planeswalkers Promos 2009",
  "pmps09": "Magic Premiere Shop 2009",
  "p09": "Magic Player Rewards 2009",
  "f09": "Friday Night Magic 2009",
  "g09": "Judge Gift Cards 2009",
  "dd2": "Duel Decks: Jace vs. Chandra",
  "tdd2": "Duel Decks: Jace vs. Chandra Tokens",
  "tala": "Shards of Alara Tokens",
  "ala": "Shards of Alara",
  "pwpn": "Wizards Play Network 2008",
  "me2": "Masters Edition II",
  "drb": "From the Vault: Dragons",
  "teve": "Eventide Tokens",
  "eve": "Eventide",
  "shm": "Shadowmoor",
  "tshm": "Shadowmoor Tokens",
  "p15a": "15th Anniversary Cards",
  "plpa": "Launch Parties",
  "mor": "Morningtide",
  "tmor": "Morningtide Tokens",
  "pmps08": "Magic Premiere Shop 2008",
  "pg08": "Gateway 2008",
  "f08": "Friday Night Magic 2008",
  "p08": "Magic Player Rewards 2008",
  "g08": "Judge Gift Cards 2008",
  "dd1": "Duel Decks: Elves vs. Goblins",
  "tdd1": "Duel Decks: Elves vs. Goblins Tokens",
  "lrw": "Lorwyn",
  "tlrw": "Lorwyn Tokens",
  "me1": "Masters Edition",
  "psum": "Summer of Magic",
  "10e": "Tenth Edition",
  "p10e": "Tenth Edition Promos",
  "t10e": "Tenth Edition Tokens",
  "fut": "Future Sight",
  "pgpx": "Grand Prix Promos",
  "ppro": "Pro Tour Promos",
  "plc": "Planar Chaos",
  "pres": "Resale Promos",
  "pg07": "Gateway 2007",
  "pmps07": "Magic Premiere Shop 2007",
  "p07": "Magic Player Rewards 2007",
  "f07": "Friday Night Magic 2007",
  "g07": "Judge Gift Cards 2007",
  "hho": "Happy Holidays",
  "tsp": "Time Spiral",
  "tsb": "Time Spiral Timeshifted",
  "tcsp": "Coldsnap Tokens",
  "csp": "Coldsnap",
  "cst": "Coldsnap Theme Decks",
  "dis": "Dissension",
  "pcmp": "Champs and States",
  "gpt": "Guildpact",
  "pal06": "Arena League 2006",
  "pmps06": "Magic Premiere Shop 2006",
  "pjas": "Junior APAC Series",
  "f06": "Friday Night Magic 2006",
  "phuk": "Hachette UK",
  "p06": "Magic Player Rewards 2006",
  "g06": "Judge Gift Cards 2006",
  "pgtw": "Gateway 2006",
  "p2hg": "Two-Headed Giant Tournament",
  "rav": "Ravnica: City of Guilds",
  "psal": "Salvat 2005",
  "9ed": "Ninth Edition",
  "sok": "Saviors of Kamigawa",
  "bok": "Betrayers of Kamigawa",
  "pal05": "Arena League 2005",
  "pmps": "Magic Premiere Shop 2005",
  "pjse": "Junior Series Europe",
  "p05": "Magic Player Rewards 2005",
  "g05": "Judge Gift Cards 2005",
  "f05": "Friday Night Magic 2005",
  "unh": "Unhinged",
  "chk": "Champions of Kamigawa",
  "wc04": "World Championship Decks 2004",
  "5dn": "Fifth Dawn",
  "dst": "Darksteel",
  "pal04": "Arena League 2004",
  "f04": "Friday Night Magic 2004",
  "g04": "Judge Gift Cards 2004",
  "p04": "Magic Player Rewards 2004",
  "mrd": "Mirrodin",
  "wc03": "World Championship Decks 2003",
  "8ed": "Eighth Edition",
  "prel": "Release Events",
  "scg": "Scourge",
  "lgn": "Legions",
  "pmoa": "Magic Online Avatars",
  "pjjt": "Japan Junior Tournament",
  "pal03": "Arena League 2003",
  "ovnt": "Vintage Championship",
  "p03": "Magic Player Rewards 2003",
  "g03": "Judge Gift Cards 2003",
  "f03": "Friday Night Magic 2003",
  "ons": "Onslaught",
  "wc02": "World Championship Decks 2002",
  "phj": "Hobby Japan Promos",
  "prm": "Magic Online Promos",
  "jud": "Judgment",
  "tor": "Torment",
  "pal02": "Arena League 2002",
  "f02": "Friday Night Magic 2002",
  "g02": "Judge Gift Cards 2002",
  "pr2": "Magic Player Rewards 2002",
  "dkm": "Deckmasters",
  "ody": "Odyssey",
  "wc01": "World Championship Decks 2001",
  "apc": "Apocalypse",
  "7ed": "Seventh Edition",
  "pls": "Planeshift",
  "pal01": "Arena League 2001",
  "mpr": "Magic Player Rewards 2001",
  "f01": "Friday Night Magic 2001",
  "g01": "Judge Gift Cards 2001",
  "inv": "Invasion",
  "btd": "Beatdown Box Set",
  "wc00": "World Championship Decks 2000",
  "pcy": "Prophecy",
  "s00": "Starter 2000",
  "nem": "Nemesis",
  "pelp": "European Land Program",
  "pal00": "Arena League 2000",
  "g00": "Judge Gift Cards 2000",
  "fnm": "Friday Night Magic 2000",
  "psus": "Junior Super Series",
  "brb": "Battle Royale Box Set",
  "mmq": "Mercadian Masques",
  "pwos": "Wizards of the Coast Online Store",
  "pwor": "Worlds",
  "wc99": "World Championship Decks 1999",
  "pgru": "Guru",
  "s99": "Starter 1999",
  "uds": "Urza's Destiny",
  "ptk": "Portal Three Kingdoms",
  "6ed": "Classic Sixth Edition",
  "ulg": "Urza's Legacy",
  "pal99": "Arena League 1999",
  "g99": "Judge Gift Cards 1999",
  "ath": "Anthologies",
  "usg": "Urza's Saga",
  "palp": "Asia Pacific Land Program",
  "wc98": "World Championship Decks 1998",
  "tugl": "Unglued Tokens",
  "ugl": "Unglued",
  "exo": "Exodus",
  "p02": "Portal Second Age",
  "sth": "Stronghold",
  "jgp": "Judge Gift Cards 1998",
  "tmp": "Tempest",
  "ppre": "Prerelease Events",
  "wc97": "World Championship Decks 1997",
  "wth": "Weatherlight",
  "por": "Portal",
  "pvan": "Vanguard Series",
  "ppod": "Portal Demo Game",
  "5ed": "Fifth Edition",
  "vis": "Visions",
  "itp": "Introductory Two-Player Set",
  "mgb": "Multiverse Gift Box",
  "mir": "Mirage",
  "pred": "Redemption Program",
  "pcel": "Celebration Cards",
  "parl": "Arena League 1996",
  "rqs": "Rivals Quick Start Set",
  "all": "Alliances",
  "ptc": "Pro Tour Collector Set",
  "hml": "Homelands",
  "rin": "Rinascimento",
  "ren": "Renaissance",
  "chr": "Chronicles",
  "ice": "Ice Age",
  "4bb": "Fourth Edition Foreign Black Border",
  "4ed": "Fourth Edition",
  "pmei": "Magazine Inserts",
  "plgm": "DCI Legend Membership",
  "fem": "Fallen Empires",
  "phpr": "HarperPrism Book Promos",
  "drk": "The Dark",
  "pdrc": "Dragon Con",
  "sum": "Summer Magic / Edgar",
  "leg": "Legends",
  "3ed": "Revised Edition",
  "fbb": "Foreign Black Border",
  "atq": "Antiquities",
  "arn": "Arabian Nights",
  "cei": "Intl. Collectors’ Edition",
  "ced": "Collectors’ Edition",
  "2ed": "Unlimited Edition",
  "leb": "Limited Edition Beta",
  "lea": "Limited Edition Alpha",
};


const simples = {
  "eld": "Throne of Eldraine",
  "c19": "Commander 2019",
  "m20": "Core Set 2020",
  "ss2": "Signature Spellbook: Gideon",
  "mh1": "Modern Horizons",
  "war": "War of the Spark",
  "rna": "Ravnica Allegiance",
  "opca": "Planechase Anthology Planes",
  "puma": "Ultimate Box Topper",
  "uma": "Ultimate Masters",
  "grn": "Guilds of Ravnica",
  "med": "Mythic Edition",
  "oc18": "Commander 2018 Oversized",
  "c18": "Commander 2018",
  "htr17": "2017 Heroes of the Realm",
  "ana": "Arena New Player Experience",
  "m19": "Core Set 2019",
  "gs1": "Global Series Jiang Yanggu & Mu Yanling",
  "ss1": "Signature Spellbook: Jace",
  "cm2": "Commander Anthology Volume II",
  "bbd": "Battlebond",
  "dom": "Dominaria",
  "ddu": "Duel Decks: Elves vs. Inventors",
  "a25": "Masters 25",
  "rix": "Rivals of Ixalan",
  "ust": "Unstable",
  "v17": "From the Vault: Transform",
  "ima": "Iconic Masters",
  "ddt": "Duel Decks: Merfolk vs. Goblins",
  "xln": "Ixalan",
  "h17": "HasCon 2017",
  "htr": "2016 Heroes of the Realm",
  "oc17": "Commander 2017 Oversized",
  "c17": "Commander 2017",
  "hou": "Hour of Devastation",
  "oe01": "Archenemy: Nicol Bolas Schemes",
  "e01": "Archenemy: Nicol Bolas",
  "cma": "Commander Anthology",
  "akh": "Amonkhet",
  "mp2": "Amonkhet Invocations",
  "w17": "Welcome Deck 2017",
  "dds": "Duel Decks: Mind vs. Might",
  "mm3": "Modern Masters 2017",
  "aer": "Aether Revolt",
  "pca": "Planechase Anthology",
  "oc16": "Commander 2016 Oversized",
  "c16": "Commander 2016",
  "kld": "Kaladesh",
  "mps": "Kaladesh Inventions",
  "ddr": "Duel Decks: Nissa vs. Ob Nixilis",
  "cn2": "Conspiracy: Take the Crown",
  "v16": "From the Vault: Lore",
  "emn": "Eldritch Moon",
  "ema": "Eternal Masters",
  "soi": "Shadows over Innistrad",
  "w16": "Welcome Deck 2016",
  "ddq": "Duel Decks: Blessed vs. Cursed",
  "ogw": "Oath of the Gatewatch",
  "oc15": "Commander 2015 Oversized",
  "c15": "Commander 2015",
  "bfz": "Battle for Zendikar",
  "exp": "Zendikar Expeditions",
  "ddp": "Duel Decks: Zendikar vs. Eldrazi",
  "v15": "From the Vault: Angels",
  "cp3": "Magic Origins Clash Pack",
  "ori": "Magic Origins",
  "mm2": "Modern Masters 2015",
  "tpr": "Tempest Remastered",
  "dtk": "Dragons of Tarkir",
  "ddo": "Duel Decks: Elspeth vs. Kiora",
  "cp2": "Fate Reforged Clash Pack",
  "frf": "Fate Reforged",
  "dvd": "Duel Decks Anthology: Divine vs. Demonic",
  "gvl": "Duel Decks Anthology: Garruk vs. Liliana",
  "evg": "Duel Decks Anthology: Elves vs. Goblins",
  "jvc": "Duel Decks Anthology: Jace vs. Chandra",
  "oc14": "Commander 2014 Oversized",
  "c14": "Commander 2014",
  "ktk": "Khans of Tarkir",
  "ddn": "Duel Decks: Speed vs. Cunning",
  "v14": "From the Vault: Annihilation",
  "m15": "Magic 2015",
  "cp1": "Magic 2015 Clash Pack",
  "ppc1": "M15 Prerelease Challenge",
  "vma": "Vintage Masters",
  "cns": "Conspiracy",
  "jou": "Journey into Nyx",
  "ddm": "Duel Decks: Jace vs. Vraska",
  "bng": "Born of the Gods",
  "oc13": "Commander 2013 Oversized",
  "c13": "Commander 2013",
  "ths": "Theros",
  "ddl": "Duel Decks: Heroes vs. Monsters",
  "v13": "From the Vault: Twenty",
  "m14": "Magic 2014",
  "mma": "Modern Masters",
  "dgm": "Dragon's Maze",
  "ddk": "Duel Decks: Sorin vs. Tibalt",
  "gtc": "Gatecrash",
  "ocm1": "Commander's Arsenal Oversized",
  "cm1": "Commander's Arsenal",
  "rtr": "Return to Ravnica",
  "ddj": "Duel Decks: Izzet vs. Golgari",
  "v12": "From the Vault: Realms",
  "m13": "Magic 2013",
  "opc2": "Planechase 2012 Planes",
  "pc2": "Planechase 2012",
  "avr": "Avacyn Restored",
  "phel": "Open the Helvault",
  "ddi": "Duel Decks: Venser vs. Koth",
  "dka": "Dark Ascension",
  "pd3": "Premium Deck Series: Graveborn",
  "isd": "Innistrad",
  "ddh": "Duel Decks: Ajani vs. Nicol Bolas",
  "v11": "From the Vault: Legends",
  "m12": "Magic 2012",
  "ocmd": "Commander 2011 Oversized",
  "pcmd": "Commander 2011 Launch Party",
  "cmd": "Commander 2011",
  "td2": "Duel Decks: Mirrodin Pure vs. New Phyrexia",
  "nph": "New Phyrexia",
  "ddg": "Duel Decks: Knights vs. Dragons",
  "mbs": "Mirrodin Besieged",
  "me4": "Masters Edition IV",
  "olgc": "Legacy Championship",
  "pd2": "Premium Deck Series: Fire and Lightning",
  "som": "Scars of Mirrodin",
  "ddf": "Duel Decks: Elspeth vs. Tezzeret",
  "v10": "From the Vault: Relics",
  "m11": "Magic 2011",
  "oarc": "Archenemy Schemes",
  "arc": "Archenemy",
  "parc": "Promotional Schemes",
  "roe": "Rise of the Eldrazi",
  "dde": "Duel Decks: Phyrexia vs. the Coalition",
  "wwk": "Worldwake",
  "h09": "Premium Deck Series: Slivers",
  "ddd": "Duel Decks: Garruk vs. Liliana",
  "zen": "Zendikar",
  "me3": "Masters Edition III",
  "ohop": "Planechase Planes",
  "hop": "Planechase",
  "v09": "From the Vault: Exiled",
  "m10": "Magic 2010",
  "arb": "Alara Reborn",
  "ddc": "Duel Decks: Divine vs. Demonic",
  "con": "Conflux",
  "dd2": "Duel Decks: Jace vs. Chandra",
  "ala": "Shards of Alara",
  "me2": "Masters Edition II",
  "drb": "From the Vault: Dragons",
  "eve": "Eventide",
  "shm": "Shadowmoor",
  "mor": "Morningtide",
  "dd1": "Duel Decks: Elves vs. Goblins",
  "lrw": "Lorwyn",
  "me1": "Masters Edition",
  "10e": "Tenth Edition",
  "fut": "Future Sight",
  "plc": "Planar Chaos",
  "hho": "Happy Holidays",
  "tsp": "Time Spiral",
  "tsb": "Time Spiral Timeshifted",
  "csp": "Coldsnap",
  "dis": "Dissension",
  "gpt": "Guildpact",
  "rav": "Ravnica: City of Guilds",
  "9ed": "Ninth Edition",
  "sok": "Saviors of Kamigawa",
  "bok": "Betrayers of Kamigawa",
  "unh": "Unhinged",
  "chk": "Champions of Kamigawa",
  "wc04": "World Championship Decks 2004",
  "5dn": "Fifth Dawn",
  "dst": "Darksteel",
  "mrd": "Mirrodin",
  "wc03": "World Championship Decks 2003",
  "8ed": "Eighth Edition",
  "scg": "Scourge",
  "lgn": "Legions",
  "ovnt": "Vintage Championship",
  "ons": "Onslaught",
  "wc02": "World Championship Decks 2002",
  "jud": "Judgment",
  "tor": "Torment",
  "ody": "Odyssey",
  "wc01": "World Championship Decks 2001",
  "apc": "Apocalypse",
  "7ed": "Seventh Edition",
  "pls": "Planeshift",
  "inv": "Invasion",
  "wc00": "World Championship Decks 2000",
  "pcy": "Prophecy",
  "s00": "Starter 2000",
  "nem": "Nemesis",
  "mmq": "Mercadian Masques",
  "wc99": "World Championship Decks 1999",
  "s99": "Starter 1999",
  "uds": "Urza's Destiny",
  "ptk": "Portal Three Kingdoms",
  "6ed": "Classic Sixth Edition",
  "ulg": "Urza's Legacy",
  "usg": "Urza's Saga",
  "wc98": "World Championship Decks 1998",
  "ugl": "Unglued",
  "exo": "Exodus",
  "p02": "Portal Second Age",
  "sth": "Stronghold",
  "tmp": "Tempest",
  "wc97": "World Championship Decks 1997",
  "wth": "Weatherlight",
  "por": "Portal",
  "ppod": "Portal Demo Game",
  "5ed": "Fifth Edition",
  "vis": "Visions",
  "itp": "Introductory Two-Player Set",
  "mir": "Mirage",
  "pcel": "Celebration Cards",
  "all": "Alliances",
  "ptc": "Pro Tour Collector Set",
  "hml": "Homelands",
  "rin": "Rinascimento",
  "ren": "Renaissance",
  "chr": "Chronicles",
  "ice": "Ice Age",
  "4bb": "Fourth Edition Foreign Black Border",
  "4ed": "Fourth Edition",
  "fem": "Fallen Empires",
  "drk": "The Dark",
  "sum": "Summer Magic / Edgar",
  "leg": "Legends",
  "3ed": "Revised Edition",
  "fbb": "Foreign Black Border",
  "atq": "Antiquities",
  "arn": "Arabian Nights",
  "cei": "Intl. Collectors’ Edition",
  "ced": "Collectors’ Edition",
  "2ed": "Unlimited Edition",
  "leb": "Limited Edition Beta",
  "lea": "Limited Edition Alpha",
};